#ifndef _IFFACM_H_
#define _IFFACM_H_

// {316C6C42-8EB7-44dc-B069-5C6078BBE37F}
DEFINE_GUID(IID_Iffacm2creator , 0x316c6c42, 0x8eb7, 0x44dc, 0xb0, 0x69, 0x5c, 0x60, 0x78, 0xbb, 0xe3, 0x7f);
// {F6E8FC04-8B05-48b1-9399-848229502A06}
DEFINE_GUID(CLSID_FFACM2CREATOR, 0xf6e8fc04, 0x8b05, 0x48b1, 0x93, 0x99, 0x84, 0x82, 0x29, 0x50, 0x2a, 0x06);

#define FFDSHOWACM_DESC_L L"ffdshow ACM codec"

DECLARE_INTERFACE_(Iffacm2creator,IUnknown)
{
 STDMETHOD_(int,getSize)(void) PURE;
 STDMETHOD (create)(void *ptr) PURE;
};

DECLARE_INTERFACE(Iffacm2)
{
 STDMETHOD_(LRESULT,driverDetails)(LPACMDRIVERDETAILSW details) PURE;
 STDMETHOD_(LRESULT,driverAbout)(HWND parent) PURE;
 STDMETHOD_(LRESULT,formatSuggest)(LPACMDRVFORMATSUGGEST padfs) PURE;
 STDMETHOD_(LRESULT,formatTagDetails)(LPACMFORMATTAGDETAILSW padft,DWORD fdwDetails) PURE;
 STDMETHOD_(LRESULT,streamOpen)(LPACMDRVSTREAMINSTANCE padsi) PURE;
 STDMETHOD_(LRESULT,streamClose)(LPACMDRVSTREAMINSTANCE padsi) PURE;
 STDMETHOD_(LRESULT,streamSize)(LPACMDRVSTREAMINSTANCE padsi,LPACMDRVSTREAMSIZE padss) PURE;
 STDMETHOD_(LRESULT,convert)(LPACMDRVSTREAMINSTANCE padsi,LPACMDRVSTREAMHEADER padsh) PURE;
};

#endif
