//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ffdshow.rc
//
#define IDC_BT_APPLY                    3
#define IDS_FFDSHOWDECVIDEO             9
#define IDS_FFDSHOWDECAUDIO             10
#define IDS_FFDSHOWENC                  11
#define IDS_FFDSHOWVFW                  12
#define IDS_FFDSHOWENCVFW               13
#define IDS_FFDSHOWDECVIDEOVFW          14
#define IDS_FFDSHOWDECVIDEORAW          15
#define IDS_FFDSHOWDECAUDIORAW          16
#define IDS_FFDSHOWDEC                  17
#define IDS_FFDSHOWVIDEOPROC            18
#define IDS_FFDSHOWDECVIDEOSUBTITLES    19
#define IDD_PAGESITE                    101
#define IDD_ABOUT                       102
#define IDD_FFDSHOW                     111
#define IDI_FFDSHOW                     112
#define IDD_SUBTITLES                   113
#define IDD_CODECS                      115
#define IDD_DIRECTSHOWCONTROL           116
#define IDD_DECODEROPTIONS              118
#define IDD_PRESETS                     119
#define IDD_POSTPROC                    120
#define IDD_QUEUE                       121
#define IDD_PICTPROP                    125
#define IDD_NOISE                       126
#define IDB_CHECKED                     127
#define IDD_SHARPEN                     127
#define IDB_CLEAR                       128
#define IDD_BLUR                        128
#define IDB_CHB_MASK                    129
#define IDD_FONT                        132
#define IDD_RESIZEASPECT                133
#define IDD_CROP                        134
#define IDD_DLGMISC                     136
#define IDD_OFFSETFLIP                  137
#define IDD_RESIZESETTINGS              138
#define IDD_SHOWMV                      139
#define IDD_DEINTERLACE                 140
#define IDD_OSD                         141
#define IDD_LEVELS                      142
#define IDD_KEYS                        143
#define IDB_ARROWS                      145
#define IDB_ARROWS_MASK_UD              146
#define IDB_ARROWS_MASK_U               147
#define IDR_MENU_PRESET                 147
#define IDB_ARROWS_MASK_D               148
#define ID_MNI_PRESET_RENAME            149
#define ID_MNI_PRESET_RENAMETOFILE      150
#define IDB_GRADIENT                    159
#define IDI_FFDSHOWAUDIO                164
#define IDD_PRESET_AUTOLOAD             171
#define IDD_GRAB                        172
#define IDD_OVERLAY                     173
#define IDD_DSCALER                     176
#define IDD_PERSPECTIVE                 177
#define IDD_DCT                         179
#define IDD_AVISYNTH                    180
#define IDD_WARPSHARP                   181
#define IDS_FFDSHOWRAW                  182
#define IDD_FFDSHOWAUDIO                182
#define IDD_ABOUTAUDIO                  184
#define IDI_FFVFW                       185
#define IDD_VOLUME                      188
#define IDD_EQ                          189
#define IDD_WINAMP2                     190
#define IDD_MIXER                       191
#define IDD_INPUTSTRING                 192
#define IDD_VERSIONS                    193
#define IDD_ABOUTENC                    193
#define IDD_GENERIC                     200
#define IDR_MENU_TRANSLATE              200
#define IDD_FFDSHOWENC                  202
#define IDD_CREDITS                     203
#define IDD_CURVEALT                    204
#define IDD_CURVENORMAL                 205
#define IDD_FIRSTPASS                   206
#define IDD_GENERIC_FFV1                207
#define IDD_GENERIC_RAW                 209
#define IDD_GENERIC_THEO                210
#define IDD_GRAPH                       211
#define IDD_GENERIC_HUFFYUV             212
#define IDD_IN                          213
#define IDD_MASKING                     214
#define IDD_MASKING_XVID                215
#define IDD_ME                          216
#define IDD_QOS                         217
#define IDD_ME_XVID                     218
#define IDD_ONEPASS                     219
#define IDD_ONEPASS_XVID                220
#define IDD_BITRATE                     221
#define IDD_OUT                         222
#define IDD_QUANT                       223
#define IDD_COMPATIBILITY               224
#define IDD_QUANT_TABLES_BASE           225
#define IDD_SECONDPASS                  226
#define IDD_PERFECT                     227
#define IDB_MODERN_ICON_XP              227
#define IDD_GENERIC_WMV9                228
#define IDD_PRESETSENC                  230
#define IDB_CLASSIC_ICON_XP             230
#define IDD_OUTCSPS                     231
#define IDI_MODERN_ICON_V               231
#define IDD_GENERIC_LJPEG               232
#define IDI_MODERN_ICON_A               232
#define IDD_HIDESHOW                    233
#define IDI_MODERN_ICON_E               233
#define IDD_MASKING_SKAL                234
#define IDD_ME_SKAL                     235
#define IDI_MODERN_4BIT_ICON_V          235
#define IDD_FREEVERB                    236
#define IDI_MODERN_4BIT_ICON_A          236
#define IDD_RESAMPLE                    237
#define IDI_MODERN_4BIT_ICON_E          237
#define IDD_ME_X264                     238
#define IDD_DEINTERLACE_TOMSMOCOMP      239
#define IDD_DEINTERLACE_FRAMEDBL        240
#define IDD_DEINTERLACE_KERNEL          241
#define IDD_LOGOAWAY                    242
#define IDD_OUTSFS                      243
#define IDD_DOLBYDECODER                244
#define IDD_DELAY                       245
#define IDD_FIR                         246
#define IDD_AUDIODENOISE                247
#define IDD_AUDIOSWITCHER               248
#define IDD_CRYSTALITY                  249
#define IDD_VOBSUB                      250
#define IDD_DEINTERLACE_DGBOB           251
#define IDD_LFECROSSOVER                252
#define IDD_CHANNELSWAP                 253
#define IDD_SUBTITLESTEXT               254
#define IDD_BITMAP                      255
#define IDD_GENERIC_X264                256
#define IDD_PROPSEDIT                   257
#define IDD_MASKING_THEO                258
#define IDD_PROCSFS                     259
#define IDD_FLIP                        260
#define IDD_RESIZEBORDERS               261
#define IDD_CONVOLVER                   262
#define IDD_LICENSE                     263
#define IDD_MOUSE                       264
#define IDD_PRESET_AUTOLOAD_ITEMS       265
#define IDD_QUANT_TABLES                266
#define IDD_QUANT_CURRENT               267
#define IDD_MASKING_X264                268
#define IDD_GENERIC_DV                  269
#define IDD_GRADFUN                     270
#define IDD_QUEUEMSG_1                  271
#define IDD_QUEUEMSG_2                  272
#define IDD_QUEUEMSG_3                  273
#define IDD_QUEUEMSG_4                  274
#define IDD_QUEUEMSG_5                  275
#define IDD_README_VIDEO                288
#define IDD_README_AUDIO                289
#define IDD_README_ENC                  290
#define IDD_QUEUEMSG_6                  292
#define IDD_QUEUEMSG_7                  293
#define IDD_QUEUEMSG_8                  294
#define IDD_COMPATIBILITY_MANAGER       295
#define IDD_DEINTERLACE_YADIF           296
#define IDD_IETR						300
#define IDC_TBR_ASPECT_USER             1002
#define IDC_TBR_PPQUAL                  1002
#define IDC_TBR_LUMGAIN                 1003
#define IDC_PLACE_PAGE                  1003
#define IDC_TBR_HUE                     1004
#define IDC_TBR_RESIZE_SHARPEN_LUM      1004
#define IDC_LINE                        1004
#define IDC_TBR_HWOVERLAY_ASPECT        1005
#define IDC_TBR_LUMOFFSET               1005
#define IDC_TBR_BORDER_HORIZ_PIXELS     1005
#define IDC_TBR_RESIZE_PARAM_LUMA       1005
#define IDC_TBR_RESIZE_SHARPEN_CHROM    1006
#define IDC_TBR_SATURATION              1006
#define IDC_TBR_FREEVERB_DRY            1006
#define IDC_TBR_BORDER_VERT_PIXELS      1006
#define IDC_TBR_GAMMA                   1007
#define IDC_TBR_RESIZE_VWARP            1007
#define IDC_CHB_AUTOQ                   1008
#define IDC_TBR_FREEVERB_WIDTH          1008
#define IDC_TBR_COLORIZESTRENGTH        1008
#define IDC_TBR_RESIZE_PARAM_CHROMA     1008
#define IDC_BT_PRESET_NEW               1016
#define IDC_CHB_FLIP                    1016
#define IDC_BT_PRESET_NEW_MENU          1017
#define IDC_LBL_LUMGAIN                 1017
#define IDC_CHB_ALLOWOUTCHANGE          1017
#define IDC_BT_PRESET_RENAME_MENU       1018
#define IDC_LBL_LUMOFFSET               1018
#define IDC_LBL_RESIZE_SHARPEN_LUM      1019
#define IDC_LBL_SHARPEN1                1019
#define IDC_LBL_FREEVERB_DRY            1019
#define IDC_LBL_RESIZE_SHARPEN_CHROM    1020
#define IDC_TBR_SHARPEN1                1020
#define IDC_CHB_OUT_YV12                1020
#define IDC_LBL_SHARPEN2                1021
#define IDC_CHB_OUT_YUY2                1021
#define IDC_LBL_RESIZE_PARAM_LUMA       1021
#define IDC_TBR_SHARPEN2                1022
#define IDC_LBL_RESIZE_VWARP            1022
#define IDC_CHB_OUT_YVYU                1022
#define IDC_TBR_BLUR_SOFTEN             1023
#define IDC_LBL_SHARPEN3                1023
#define IDC_LBL_RESIZE_PARAM_CHROMA     1023
#define IDC_TBR_BLUR_TEMPSMOOTH         1024
#define IDC_TBR_OVERLAY_CONTRAST        1024
#define IDC_TBR_SHARPEN3                1024
#define IDC_LBL_HUE                     1025
#define IDC_TBR_BLUR_SMOOTHLUMA         1025
#define IDC_TBR_OVERLAY_HUE             1025
#define IDC_LBL_SATURATION              1026
#define IDC_TBR_BLUR_SMOOTHCHROMA       1026
#define IDC_TBR_OVERLAY_SATURATION      1026
#define IDC_RBT_PPPRESETS               1027
#define IDC_TBR_BLUR_GRADUAL            1027
#define IDC_TBR_OVERLAY_SHARPNESS       1027
#define IDC_CHB_OUT_UYVY                1027
#define IDC_RBT_PPCUSTOM                1028
#define IDC_TBR_BLUR_MPLAYER1           1028
#define IDC_TBR_OVERLAY_GAMMA           1028
#define IDC_CHB_OUT_RGB24               1028
#define IDC_CHB_DEBLOCKV_LUM            1029
#define IDC_TBR_BLUR_MPLAYER2           1029
#define IDC_CHB_OUT_RGB16               1029
#define IDC_CHB_DEBLOCKH_LUM            1030
#define IDC_TBR_BLUR_MPLAYER3           1030
#define IDC_CHB_OUT_RGB15               1030
#define IDC_CHB_DERING_LUM              1031
#define IDC_CHB_HWOVERLAY               1031
#define IDC_TBR_BLUR_SWSCALER_RADIUS    1031
#define IDC_CHB_DEBLOCKV_CHROM          1032
#define IDC_TBR_BLUR_SWSCALER_LUMA      1032
#define IDC_CHB_OUT_I420                1032
#define IDC_CHB_DEBLOCKH_CHROM          1033
#define IDC_TBR_BLUR_SWSCALER_CHROMA    1033
#define IDC_CHB_HWDEINTERLACE           1033
#define IDC_CHB_DERING_CHROM            1034
#define IDC_TBR_BLUR_DENOISE3D_LUMA     1034
#define IDC_CHB_OUTCHANGECOMPATONLY     1034
#define IDC_CHB_LEVELFIX_LUM            1035
#define IDC_TBR_BLUR_DENOISE3D_CHROMA   1035
#define IDC_CHB_OUT_DV                  1035
#define IDC_TBR_BLUR_DENOISE3D_TIME     1036
#define IDC_CHB_OUT_CLOSESTMATCH        1036
#define IDC_LBL_GAMMA                   1037
#define IDC_CHB_OUT_NV12                1037
#define IDC_CHB_FULLYRANGE              1038
#define IDC_CHB_NOISE                   1038
#define IDC_LBL_GAMMARGB                1038
#define IDC_LBL_FREEVERB_WIDTH          1038
#define IDC_CHB_NOISE_UNIFORM           1039
#define IDC_TBR_NOISESTRENGTH           1040
#define IDC_LBL_NOISESTRENGTH           1041
#define IDC_BT_PRESET_REMOVE            1044
#define IDC_BT_PRESET_RENAME            1045
#define IDC_LBL_IDCT                    1045
#define IDC_CBX_IDCT                    1046
#define IDC_LBL_BUGS                    1047
#define IDC_LBL_NOISESTRENGTH_CHROMA    1049
#define IDC_LBL_FLICKER                 1050
#define IDC_CHB_AUTOPRESET              1051
#define IDC_CHB_OUT_RGB32               1051
#define IDC_LBL_SHAKE                   1051
#define IDC_LBL_LINES                   1052
#define IDC_CHB_AVISYNTH_YV12_RGB       1052
#define IDC_TBR_NOISESTRENGTH_CHROMA    1053
#define IDC_LBL_SCRATCHES               1054
#define IDC_RBT_SHARPEN_XSHARPEN        1063
#define IDC_RBT_SHARPEN_UNSHARPMASK     1064
#define IDC_CHB_SHARPEN                 1065
#define IDC_RBT_SHARPEN_MSHARPEN        1066
#define IDC_RBT_NOISE_MOJ               1067
#define IDC_RBT_NOISE_AVIH              1068
#define IDC_RBT_SHARPEN_ASHARP          1068
#define IDC_RBT_NOISE_MP                1069
#define IDC_RBT_SHARPEN_MPLAYER         1069
#define IDC_CHB_TRAYICON                1070
#define IDC_CHB_DLG_RESTOREPOS          1071
#define IDC_CHB_DLG_SHOWHINTS           1072
#define IDC_CHB_PICTPROP                1072
#define IDC_LBL_FFDSHOWVERSION          1072
#define IDC_CHB_POSTPROC                1073
#define IDC_CHB_STREAMSMENU             1073
#define IDC_CHB_VIS_MV                  1074
#define IDC_CHB_TRAYICONEXT             1074
#define IDC_CHB_VIS_QUANTS              1075
#define IDC_CHB_AUTOPRESET_FILEFIRST    1080
#define IDC_CHB_RESIZE                  1083
#define IDC_ED_RESIZEDX                 1084
#define IDC_ED_RESIZEDY                 1085
#define IDC_ED_CROP_TOP                 1086
#define IDC_ED_RESIZEA1                 1086
#define IDC_ED_CROP_LEFT                1087
#define IDC_ED_RESIZEA2                 1087
#define IDC_ED_RESIZE_IFX               1088
#define IDC_ED_CROP_RIGHT               1089
#define IDC_ED_RESIZE_IFY               1089
#define IDC_ED_RESIZE_IFPIX             1090
#define IDC_CBX_RESIZE_METHOD_LUMA      1090
#define IDC_CBX_RESIZE_METHOD_CHROMA    1091
#define IDC_ED_CROP_BOTTOM              1092
#define IDC_LBL_RESIZE_GBLUR_LUM        1098
#define IDC_LBL_RESIZE_GBLUR_CHROM      1099
#define IDC_RBT_ASPECT_NO               1100
#define IDC_LBL_RESIZE_HWARP            1100
#define IDC_RBT_ASPECT_KEEP             1101
#define IDC_RBT_ASPECT_USER             1102
#define IDC_TBR_RESIZE_GBLUR_LUM        1103
#define IDC_TBR_RESIZE_GBLUR_CHROM      1104
#define IDC_CHB_SUBTITLES               1105
#define IDC_LBL_ZOOMX                   1105
#define IDC_TBR_RESIZE_HWARP            1105
#define IDC_TBR_ZOOMX                   1106
#define IDC_LBL_ZOOMY                   1107
#define IDC_LBL_FONT_WEIGHT             1108
#define IDC_TBR_ZOOMY                   1108
#define IDC_CBX_FONT_WEIGHT             1109
#define IDC_LBL_PANSCAN_ZOOM            1109
#define IDC_LBL_FONT_SIZE               1110
#define IDC_TBR_PANSCAN_ZOOM            1110
#define IDC_LBL_PANSCAN_X               1111
#define IDC_TBR_FONT_SIZE               1111
#define IDC_CBX_FONT_NAME               1112
#define IDC_TBR_PANSCAN_X               1112
#define IDC_CBX_FONT_CHARSET            1113
#define IDC_LBL_PANSCAN_Y               1113
#define IDC_LBL_FONT_CHARSET            1114
#define IDC_TBR_PANSCAN_Y               1114
#define IDC_CBX_FONT_NAME2              1115
#define IDC_LBL_FONT_SPACING            1116
#define IDC_TBR_FONT_SPACING            1117
#define IDC_LBL_FONT_OUTLINE_STRENGTH   1118
#define IDC_TBR_FONT_OUTLINE_STRENGTH   1119
#define IDC_BT_SUB_LOADFILE             1120
#define IDC_LBL_OFFSETUV_Y              1120
#define IDC_LBL_FONT_XSCALE             1120
#define IDC_CBX_SUB_FLNM                1121
#define IDC_TBR_OFFSETUV_Y              1121
#define IDC_TBR_FONT_XSCALE             1121
#define IDC_LBL_SUB_POSX                1122
#define IDC_TBR_SUB_POSX                1123
#define IDC_BT_SUB_SEARCHDIR            1124
#define IDC_LBL_FONT_COLOR              1124
#define IDC_IMG_FONT_COLOR              1125
#define IDC_LBL_SUB_POSY                1126
#define IDC_TBR_SUB_POSY                1127
#define IDC_ED_SUB_DELAY                1128
#define IDC_ED_SUB_SPEED                1129
#define IDC_ED_SUB_SPEED2               1130
#define IDC_TBR_SUB_STEREOSCOPICPAR     1131
#define IDC_TBR_SUB_LINESPACING         1132
#define IDC_CHB_BLUR                    1134
#define IDC_CHB_BLUR_SOFTEN             1136
#define IDC_CHB_CROP                    1137
#define IDC_CHB_BLUR_TEMPSMOOTH         1137
#define IDC_LBL_OVERLAY_CONTRAST        1137
#define IDC_CHB_BLUR_SMOOTHLUMA         1138
#define IDC_LBL_OVERLAY_HUE             1138
#define IDC_RBT_ZOOM                    1138
#define IDC_CHB_BLUR_SMOOTHCHROMA       1139
#define IDC_LBL_OVERLAY_SATURATION      1139
#define IDC_RBT_CROP                    1139
#define IDC_CHB_MAGNIFICATION_LOCKED    1140
#define IDC_CHB_BLUR_GRADUAL            1140
#define IDC_LBL_OVERLAY_SHARPNESS       1140
#define IDC_CHB_BLUR_MPLAYER            1141
#define IDC_LBL_OVERLAY_GAMMA           1141
#define IDC_RBT_PANSCAN                 1141
#define IDC_TV_TREE                     1141
#define IDC_CHB_BLUR_SWSCALER           1142
#define IDC_ED_HELP                     1143
#define IDC_LV_PRESETS                  1144
#define IDC_ED_LICENSE                  1144
#define IDC_CHB_OFFSET                  1148
#define IDC_LBL_OFFSETY_X               1149
#define IDC_TBR_OFFSETY_X               1150
#define IDC_LBL_OFFSETY_Y               1151
#define IDC_TBR_OFFSETY_Y               1152
#define IDC_LBL_OFFSETUV_X              1153
#define IDC_TBR_OFFSETUV_X              1154
#define IDC_BT_PRESET_SAVETOFILE        1155
#define IDC_BT_PRESET_READFROMFILE      1156
#define IDC_BT_AUTOPRESET               1157
#define IDC_LBL_DEBLOCKSTRENGTH         1158
#define IDC_TBR_DEBLOCKSTRENGTH         1159
#define IDC_LBL_PP_METHOD               1160
#define IDC_TOPLINE                     1161
#define IDC_BT_RESET                    1162
#define IDC_BT_HELP                     1163
#define IDC_CHB_PROCESSFULL             1164
#define IDC_CBX_PRESETS                 1165
#define IDC_TOPLINE2                    1166
#define IDC_CHB_DEINTERLACE             1167
#define IDC_CHB_PROCESSHALF             1167
#define IDC_CHB_LEVELS                  1170
#define IDC_BMP_HISTOGRAM               1176
#define IDC_BMP_LEVELS_IN               1177
#define IDC_BMP_LEVELS_OUT              1178
#define IDC_CHB_LEVELS_ONLYLUMA         1179
#define IDC_TBR_LEVELS_GAMMA            1180
#define IDC_LBL_LEVELS_GAMMA            1181
#define IDC_CHB_OSD                     1182
#define IDC_BMP_LEVELS_CURVES           1182
#define IDC_RBT_SUB_FLNM                1183
#define IDC_CHB_LEVELS_SHOW_HISTOGRAM   1184
#define IDC_CHB_LEVELS_SHOW_HISTOGRAM_FULL 1185
#define IDC_RBT_RESIZE_MODE_ASPECT      1186
#define IDC_RBT_RESIZE_MOD_16           1187
#define IDC_RBT_RESIZE_ALWAYS           1188
#define IDC_TBR_LEVELS_POSTERIZE        1188
#define IDC_RBT_RESIZE_IFSIZE           1189
#define IDC_LBL_LEVELS_POSTERIZE        1189
#define IDC_BT_RESIZE_XYCOND            1190
#define IDC_RBT_RESIZE_IFNUMBEROFPIXELS 1191
#define IDC_BT_RESIZE_PIXCOND           1192
#define IDC_BT_RESIZE_XCOND             1193
#define IDC_BT_RESIZE_YCOND             1194
#define IDC_BT_RESIZE_ASPECT_MENU       1195
#define IDC_BT_RESIZE_SIZE_MENU         1196
#define IDC_BT_RESIZE_PIX_MENU          1197
#define IDC_BT_RESIZE_MOD_16            1198
#define IDC_CHB_BORDERSLOCKED           1199
#define IDC_CHB_KEYS                    1202
#define IDC_LV_KEYS                     1205
#define IDC_ED_PRESETAUTOLOAD_SIZE_XMIN 1206
#define IDC_ED_VIDEODELAY               1206
#define IDC_ED_PRESETAUTOLOAD_SIZE_XMAX 1207
#define IDC_LBL_TOMSMOCOMP_SEARCH       1207
#define IDC_ED_VIDEODELAYEND            1207
#define IDC_ED_PRESETAUTOLOAD_SIZE_YMIN 1208
#define IDC_TBR_TOMSMOCOMP_SEARCH       1208
#define IDC_CHB_SWAP_FIELDS             1209
#define IDC_ED_PRESETAUTOLOAD_SIZE_YMAX 1209
#define IDC_CHB_TOMSMOCOMP_VF           1210
#define IDC_CHB_PRESETAUTOLOAD_SIZE     1211
#define IDC_TBR_FRAMEDOUBLE_THRESHOLD   1211
#define IDC_LBL_AUTOLOAD                1212
#define IDC_LBL_FRAMEDOUBLE_SE          1212
#define IDC_CHB_SHARPEN_MSHARPEN_MASK   1215
#define IDC_CHB_GRAB                    1216
#define IDC_CHB_SHARPEN_MSHARPEN_HQ     1216
#define IDC_ED_GRAB_PATH                1217
#define IDC_CHB_SHARPEN_ASHARP_HQBF     1217
#define IDC_BT_GRAB_PATH                1218
#define IDC_ED_GRAB_NAME                1219
#define IDC_ED_GRAB_FRAMENUM            1220
#define IDC_CBX_GRAB_DIGITS             1221
#define IDC_CBX_GRAB_FORMAT             1222
#define IDC_RBT_GRAB_EVERY              1223
#define IDC_RBT_GRAB_SINGLE             1224
#define IDC_ED_GRAB_FRAMENUM1           1225
#define IDC_RBT_GRAB_RANGE              1226
#define IDC_ED_GRAB_FRAMENUM2           1227
#define IDC_BT_GRAB_NOW                 1228
#define IDC_TBR_GRAB_QUAL               1229
#define IDC_LBL_GRAB_QUAL               1230
#define IDC_CHB_NOISE_PATTERN           1231
#define IDC_ED_GRAB_STEP                1231
#define IDC_LBL_GRAB_PATH               1232
#define IDC_CHB_BLUR_TEMPSMOOTH_COLOR   1232
#define IDC_CHB_NOISE_AVG               1232
#define IDC_LBL_HWOVERLAY_ASPECT        1234
#define IDC_CHB_OVERLAY                 1235
#define IDC_LBL_OVERLAY_BRIGHTNESS      1236
#define IDC_TBR_OVERLAY_BRIGHTNESS      1237
#define IDC_CHB_POSTPROC_MPLAYER        1238
#define IDC_CHB_POSTPROC_NIC            1239
#define IDC_TBR_POSTPROC_NIC_XTHRES     1240
#define IDC_TBR_POSTPROC_NIC_YTHRES     1241
#define IDC_LBL_POSTPROC_NIC_XTHRES     1242
#define IDC_LBL_POSTPROC_NIC_YTHRES     1243
#define IDC_BT_SUB_LOAD                 1244
#define IDC_ED_SUB_SEARCH_DIR           1246
#define IDC_BT_OSD_LINE_UP              1248
#define IDC_BT_OSD_LINE_DOWN            1249
#define IDC_LV_OSD_LINES                1250
#define IDC_LBL_FFDSHOW                 1251
#define IDC_BT_OSD_PRESETS              1251
#define IDC_LBL_CROP_TOP                1252
#define IDC_BT_OSD_SAVE                 1252
#define IDC_LBL_CROP_LEFT               1254
#define IDC_LBL_CROP_RIGHT              1255
#define IDC_LBL_CROP_BOTTOM             1256
#define IDC_GRP_TRAYICON                1257
#define IDC_GRP_CFGDLG                  1258
#define IDC_GRP_FONT                    1259
#define IDC_GRP_PATHS                   1259
#define IDC_GRP_OSDFONT                 1260
#define IDC_LBL_GRAB_PREFIX             1261
#define IDC_LBL_GRAB_FORMAT             1262
#define IDC_LBL_GRAB_DIGITS             1263
#define IDC_LBL_LEVELS_OUTPUT           1267
#define IDC_LBL_VIDEODELAY              1268
#define IDC_LBL_VIDEODELAY_MS           1269
#define IDC_LBL_PP_CUSTOM_LUMA          1270
#define IDC_LBL_VIDEODELAYEND_MS        1270
#define IDC_LBL_PP_CUSTOM_CHROMA        1271
#define IDC_LBL_PP_CUSTOM_DEBLOCK_H     1272
#define IDC_LBL_PP_CUSTOM_DEBLOCK_V     1273
#define IDC_LBL_PP_CUSTOM_DERING        1274
#define IDC_LBL_PP_LEVELFIX             1275
#define IDC_LBL_PRESETAUTOLOAD_WIDTH    1276
#define IDC_LBL_PRESETAUTOLOAD_HEIGHT   1277
#define IDC_GRP_PRESETS                 1278
#define IDC_RBT_SUB_SEARCHDIR           1279
#define IDC_LBL_SUB_DELAY               1280
#define IDC_LBL_SUB_SPEED               1281
#define IDC_GRP_RESIZE_SETTINGS         1282
#define IDC_LBL_SUB_DELAYMS             1282
#define IDC_GRP_LIBAVCODEC              1283
#define IDC_GRP_CSP_OUT                 1284
#define IDC_GRP_INFO                    1284
#define IDC_LBL_SUB_SPEED2              1284
#define IDC_LBL_NEW_SIZE                1285
#define IDC_GRP_DEBUG                   1285
#define IDC_LBL_RESIZE_METHOD_LUMA      1285
#define IDC_LBL_NEW_ASPECT              1286
#define IDC_LBL_RESIZE_METHOD_CHROMA    1286
#define IDC_LBL_RESIZE_IFX              1287
#define IDC_LBL_RESIZE_IFY              1288
#define IDC_GRP_ASPECT_RATIO            1289
#define IDC_LBL_LEVELS_INPUT            1291
#define IDC_CBX_LANG                    1292
#define IDC_LBL_LANG                    1293
#define IDC_CHB_WORKAROUND_AUTODETECT   1307
#define IDC_CHB_DSCALER                 1308
#define IDC_CHB_WORKAROUND_OLDMSMPEG4   1308
#define IDC_CHB_WORKAROUND_XVIDILACE    1309
#define IDC_LBL_DSCALER_FLTFLNM         1309
#define IDC_CBX_DSCALER_FLTFLNM         1310
#define IDC_CHB_WORKAROUND_UMP4         1310
#define IDC_BT_DSCALER_FLTFLNM          1311
#define IDC_CHB_WORKAROUND_NOPADDING    1311
#define IDC_CHB_WORKAROUND_AMV          1312
#define IDC_CHB_WORKAROUND_QPELCHROMA   1313
#define IDC_CHB_GRAY                    1314
#define IDC_SEP_DSCALER                 1315
#define IDC_CHB_WORKAROUND_EDGE         1315
#define IDC_CHB_HUFFYUV_CTX             1315
#define IDC_PLC_DSCALER                 1316
#define IDC_CHB_WORKAROUND_HPELCHROMA   1316
#define IDC_CHB_PERSPECTIVE             1317
#define IDC_CHB_WORKAROUND_DC_CLIP      1317
#define IDC_BMP_PERSPECTIVE             1318
#define IDC_LBL_PERSPECTIVE_INTERPOLATION 1319
#define IDC_CBX_PERSPECTIVE_INTERPOLATION 1320
#define IDC_CHB_PERSPECTIVE_ISSRC       1321
#define IDC_LBL_NEW_ASPECT_SEP          1322
#define IDC_GRP_DSCALER                 1323
#define IDC_CHB_DCT                     1324
#define IDC_RBT_DCT_COEFFS              1325
#define IDC_ED_DCT0                     1326
#define IDC_ED_DCT1                     1327
#define IDC_ED_DCT2                     1328
#define IDC_CHB_POSTPROC_NIC_FIRST      1328
#define IDC_ED_DCT3                     1329
#define IDC_CHB_KEYS_ALWAYS             1329
#define IDC_CHB_AVISYNTH                1330
#define IDC_CHB_KEYS_SHORTOSD           1330
#define IDC_ED_AVISYNTH                 1331
#define IDC_ED_DCT4                     1335
#define IDC_CHB_FONT_AUTOSIZE           1335
#define IDC_ED_DCT5                     1336
#define IDC_ED_DCT6                     1337
#define IDC_CHB_VISUALIZATIONS          1337
#define IDC_ED_DCT7                     1338
#define IDC_CHB_WARPSHARP               1338
#define IDC_RBT_WARPSHARP_WARPSHARP     1339
#define IDC_RBT_WARPSHARP_AWARPSHARP    1340
#define IDC_LBL_WARPSHARP_AWARPSHARP_CM 1341
#define IDC_CBX_WARPSHARP_AWARPSHARP_CM 1342
#define IDC_LBL_WARPSHARP_AWARPSHARP_BM 1343
#define IDC_CBX_WARPSHARP_AWARPSHARP_BM 1344
#define IDC_TBR_GAMMAR                  1345
#define IDC_TBR_GAMMAG                  1346
#define IDC_TBR_GAMMAB                  1347
#define IDC_LV_INCODECS                 1354
#define IDC_CBX_INCODECS                1355
#define IDC_CHB_VIS_GRAPH               1357
#define IDC_CHB_SUBTITLES_EXPAND        1358
#define IDC_CHB_RESIZE_INTERLACED       1360
#define IDC_LBL_SUBTITLES_ALIGN         1360
#define IDC_CBX_SUBTITLES_ALIGN         1361
#define IDC_LBL_BITMAP_MODE             1361
#define IDC_BT_SUBTITLES_RESET          1364
#define IDC_GRP_MISC                    1365
#define IDC_CBX_FRAMEDOUBLE_SE          1366
#define IDC_LBL_FRAMEDOUBLE_THRESHOLD   1367
#define IDC_LBL_VOLUME_MASTER           1375
#define IDC_TBR_VOLUME_MASTER           1376
#define IDC_CHB_VOLUME                  1377
#define IDC_CHB_EQ                      1378
#define IDC_TBR_EQ0                     1379
#define IDC_TBR_EQ1                     1381
#define IDC_TBR_EQ2                     1383
#define IDC_TBR_EQ3                     1385
#define IDC_TBR_EQ4                     1387
#define IDC_TBR_EQ5                     1389
#define IDC_TBR_EQ6                     1391
#define IDC_TBR_EQ7                     1393
#define IDC_TBR_EQ8                     1395
#define IDC_TBR_EQ9                     1397
#define IDC_ED_EQ_HIGHDB                1399
#define IDC_ED_EQ_LOWDB                 1400
#define IDC_CHB_WINAMP2                 1400
#define IDC_BT_WINAMP2_DIR              1401
#define IDC_LBL_EQDB0                   1401
#define IDC_LBX_WINAMP2_DSPS            1402
#define IDC_LBL_EQDB1                   1402
#define IDC_CBX_WINAMP2_FILTERS         1403
#define IDC_LBL_EQDB2                   1403
#define IDC_BT_WINAMP2_CONFIG           1404
#define IDC_LBL_EQDB3                   1404
#define IDC_CHB_MIXER                   1405
#define IDC_LBL_EQDB4                   1405
#define IDC_LBL_MIXER_OUT               1406
#define IDC_LBL_EQDB5                   1406
#define IDC_CBX_MIXER_OUT               1407
#define IDC_LBL_EQDB6                   1407
#define IDC_LBL_INPUTSTRING             1408
#define IDC_LBL_EQDB7                   1408
#define IDC_ED_INPUTSTRING              1409
#define IDC_LBL_EQDB8                   1409
#define IDC_LBL_EQDB9                   1410
#define IDC_CHB_SUB_WATCH               1414
#define IDC_CHB_BLUR_DENOISE3DHQ        1415
#define IDC_LBL_KEYS_SEEK1              1416
#define IDC_ED_KEYS_SEEK1               1417
#define IDC_LBL_KEYS_SEEK2              1418
#define IDC_LBL_BR_FPS                  1418
#define IDC_ED_KEYS_SEEK2               1419
#define IDC_LBL_BR_LEN                  1419
#define IDC_LBL_MAXKEYINTERVAL          1420
#define IDC_LBL_CURVENORMAL_LOW1        1420
#define IDC_TBR_MAXKEYINTERVAL          1421
#define IDC_LBL_CURVENORMAL_LOW2        1421
#define IDC_LBL_MINKEYINTERVAL          1422
#define IDC_LBL_CURVENORMAL_BITRATEPAYBACKDELAY1 1422
#define IDC_TBR_MINKEYINTERVAL          1423
#define IDC_LBL_CURVENORMAL_BITRATEPAYBACKDELAY2 1423
#define IDC_CHB_B                       1424
#define IDC_LBL_STATS1                  1424
#define IDC_LBL_KEYSCENECHANGE          1424
#define IDC_LBL_B_MAX                   1425
#define IDC_LBL_FFV1_CSP                1425
#define IDC_TBR_KEYSCENECHANGE          1425
#define IDC_ED_B_MAX                    1426
#define IDC_LBL_FFV1_CODER              1426
#define IDC_CHB_B_DYNAMIC               1427
#define IDC_LBL_FFV1_CONTEXT            1427
#define IDC_CHB_PACKEDBITSTREAM         1428
#define IDC_LBL_HUFFYUV_CSP             1428
#define IDC_CHB_DX50BVOP                1429
#define IDC_LBL_HUFFYUV_PRED            1429
#define IDC_ED_NUMTHREADS               1430
#define IDC_LBL_VRATETOL2               1431
#define IDC_CHB_B_REFINE                1431
#define IDC_LBL_VQCOMP2                 1432
#define IDC_LBL_VQBLUR12                1433
#define IDC_LBL_VQBLUR22                1434
#define IDC_LBL_XVID_REACTION_DELAY_FACTOR 1435
#define IDC_LBL_MIN_BITRATE2            1435
#define IDC_LBL_XVID_AVERAGING_PERIOD   1436
#define IDC_LBL_XVID_BUFFER             1437
#define IDC_GRP_OUTPUT                  1438
#define IDC_LBL_PERFECT_QUANT_PERCENTS  1439
#define IDC_LBL_PERFECT_QUANT_CNT       1440
#define IDC_LBL_QUANT_TYPE              1441
#define IDC_LBL_QUANT_MIN               1442
#define IDC_LBL_QUANT_MAX               1443
#define IDC_LBL_MAX_BITRATE1            1444
#define IDC_LBL_MAX_BITRATE2            1445
#define IDC_LBL_ENCODER                 1446
#define IDC_LBL_MAX_OVERFLOW_IMPR1      1446
#define IDC_LBL_BUFFER_SIZE2            1446
#define IDC_CBX_ENCODER                 1447
#define IDC_LBL_MAX_OVERFLOW_IMPR2      1447
#define IDC_LBL_FOURCC                  1448
#define IDC_LBL_MAX_OVERFLOW_DEGR1      1448
#define IDC_CBX_FOURCC                  1449
#define IDC_LBL_MAX_OVERFLOW_DEGR2      1449
#define IDC_LBL_MODES                   1450
#define IDC_LBL_KFBOOST1                1450
#define IDC_CBX_MODES                   1451
#define IDC_LBL_KFBOOST2                1451
#define IDC_LBL_KFTRESHOLD1             1452
#define IDC_LBL_QUICK                   1453
#define IDC_LBL_KFTRESHOLD2             1453
#define IDC_ED_QUICK                    1454
#define IDC_LBL_KFREDUCTION1            1454
#define IDC_TBR_QUICK                   1455
#define IDC_LBL_KFREDUCTION2            1455
#define IDC_CHB_POSTPROC_SPP            1456
#define IDC_CHB_VOLUME_NORMALIZE        1457
#define IDC_CHB_POSTPROC_FSPP           1457
#define IDC_BT_PRESET                   1459
#define IDC_CHB_POSTPROC_SPP_SOFT       1459
#define IDC_CHB_NOT_REGISTRY            1460
#define IDC_LBL_LAVC_NR                 1460
#define IDC_CHB_IS_CREDITS_START        1461
#define IDC_LBL_CREDITS_START_START     1462
#define IDC_GRP_BOOST                   1462
#define IDC_ED_CREDITS_START_START      1463
#define IDC_LBL_CURVENORMAL_HIGH1       1463
#define IDC_LBL_CREDITS_START_END       1464
#define IDC_LBL_CURVENORMAL_HIGH2       1464
#define IDC_ED_CREDITS_START_END        1465
#define IDC_LBL_EQ_HIGHDB               1465
#define IDC_CHB_IS_CREDITS_END          1466
#define IDC_LBL_EQ_LOWDB                1466
#define IDC_LBL_CREDITS_END_START       1467
#define IDC_LBL_PRESETS                 1467
#define IDC_ED_CREDITS_END_START        1468
#define IDC_LBL_PRESETENC               1468
#define IDC_LBL_CREDITS_END_END         1469
#define IDC_CBX_OSD_PRESETS             1469
#define IDC_ED_CREDITS_END_END          1470
#define IDC_LBL_LJPEG_CSP               1470
#define IDC_GRP_CREDITS_REDUCTION       1471
#define IDC_CBX_LJPEG_CSP               1471
#define IDC_RBT_CREDITS_PERCENT         1472
#define IDC_CHB_REMOTE                  1472
#define IDC_LBL_LJPEG_CSP2              1472
#define IDC_TBR_CREDITS_PERCENT         1473
#define IDC_LBL_HIDESHOW_AVAILABLE      1473
#define IDC_RBT_CREDITS_QUANT           1474
#define IDC_LBL_HIDESHOW_VISIBLE        1474
#define IDC_LBL_CREDITS_I_QUANT         1475
#define IDC_LBX_HIDESHOW_AVAILABLE      1475
#define IDC_ED_CREDITS_I_QUANT          1476
#define IDC_LBX_HIDESHOW_VISIBLE        1476
#define IDC_LBL_CREDITS_P_QUANT         1477
#define IDC_BT_HIDESHOW_SHOW            1477
#define IDC_ED_CREDITS_P_QUANT          1478
#define IDC_BT_HIDESHOW_HIDE            1478
#define IDC_CHB_SKAL_MASKING            1478
#define IDC_RBT_CREDITS_SIZE            1479
#define IDC_LBL_SKAL_MASKING            1479
#define IDC_BT_HIDESHOW_HIDE_ALL        1479
#define IDC_LBL_CREDITS_SIZE_START      1480
#define IDC_ED_SKAL_MASKING             1480
#define IDC_BT_HIDESHOW_SHOW_ALL        1480
#define IDC_ED_CREDITS_SIZE_START       1481
#define IDC_LBL_SKAL_SEARCHMETRIC       1481
#define IDC_LBL_CREDITS_SIZE_END        1482
#define IDC_CBX_SKAL_SEARCHMETRIC       1482
#define IDC_ED_CREDITS_SIZE_END         1483
#define IDC_LV_VERSIONS                 1483
#define IDC_CHB_CREDITS_GRAY            1484
#define IDC_CHB_FREEVERB                1484
#define IDC_CHB_USE_ALT_CURVE           1485
#define IDC_LBL_FREEVERB_ROOMSIZE       1485
#define IDC_LBL_CURVE_TYPE              1486
#define IDC_TBR_FREEVERB_ROOMSIZE       1486
#define IDC_CBX_CURVE_TYPE              1487
#define IDC_LBL_FREEVERB_DAMPING        1487
#define IDC_LBL_CURVEALT_DISTHIGH       1488
#define IDC_TBR_FREEVERB_DAMPING        1488
#define IDC_ED_CURVEALT_DISTHIGH        1489
#define IDC_TBR_FREEVERB_WET            1489
#define IDC_LBL_CURVEALT_DISTHIGH_PERCENT 1490
#define IDC_LBL_FREEVERB_WET            1490
#define IDC_LBL_CURVEALT_DISTLOW        1491
#define IDC_CHB_OSD_USER                1491
#define IDC_ED_CURVEALT_DISTLOW         1492
#define IDC_ED_OSD_USER                 1492
#define IDC_LBL_CURVEALT_DISTLOW_PERCENT 1493
#define IDC_LV_GENERIC                  1493
#define IDC_CHB_OSD_SAVE                1493
#define IDC_RBT_CURVEALT_USEAUTO        1494
#define IDC_GRP_GENERIC                 1494
#define IDC_ED_OSD_SAVE                 1494
#define IDC_ED_CURVEALT_AUTOSTR         1495
#define IDC_LBL_CURVEALT_AUTOSTR        1496
#define IDC_ED_RESAMPLE_FREQ            1496
#define IDC_RBT_CURVEALT_USEMANUAL      1497
#define IDC_CHB_RESAMPLE                1497
#define IDC_ED_CURVEALT_MINRELQUAL      1498
#define IDC_LBL_RESAMPLE_FREQ           1498
#define IDC_LBL_CURVEALT_MINRELQUAL     1499
#define IDC_LBL_RESAMPLE_MODE           1499
#define IDC_CHB_CURVEALT_BONUSBIASMANUAL 1500
#define IDC_CBX_RESAMPLE_MODE           1500
#define IDC_ED_CURVEALT_BONUSBIAS       1501
#define IDC_LBL_RESAMPLE_FREQ2          1501
#define IDC_CBX_MULTIPLE_INSTANCES      1501
#define IDC_ED_CURVENORMAL_HIGH         1502
#define IDC_LBL_MULTIPLE_INSTANCES      1502
#define IDC_ED_CURVENORMAL_LOW          1503
#define IDC_LBL_MERIT                   1503
#define IDC_ED_CURVENORMAL_BITRATEPAYBACKDELAY 1504
#define IDC_RBT_CURVENORMAL_PAYBACKWITHBIAS 1505
#define IDC_RBT_CURVENORMAL_PAYBACKPROPORTIONALLY 1506
#define IDC_LBL_X264_ME_INTRA           1506
#define IDC_ED_STATS1                   1507
#define IDC_CHB_X264_ME_INTRA_I4x4      1507
#define IDC_BT_STATS1                   1508
#define IDC_LBL_X264_ME_INTER           1508
#define IDC_CBX_FFV1_CSP                1509
#define IDC_CHB_X264_ME_INTRA_I8x8      1509
#define IDC_CBX_FFV1_CODER              1510
#define IDC_CHB_X264_ME_INTER_I4x4      1510
#define IDC_ED_FFV1_CONTEXT             1511
#define IDC_CHB_X264_ME_INTER_I8x8      1511
#define IDC_CBX_FFV1_CODER2             1512
#define IDC_CBX_FFV1_CONTEXT            1512
#define IDC_ED_MAXKEYINTERVAL           1513
#define IDC_CHB_X264_ME_INTER_PSUB16x16 1517
#define IDC_CHB_X264_ME_INTER_PSUB8x8   1518
#define IDC_LBL_X264_REF_FRAMES         1519
#define IDC_ED_X264_REF_FRAMES          1520
#define IDC_CHB_X264_ME_INTRA_PSUB16x16 1521
#define IDC_CHB_X264_ME_INTRA_PSUB8x8   1522
#define IDC_LBL_DEINT_METHOD            1523
#define IDC_CHB_X264_ME_INTRA_BSUB16x16 1523
#define IDC_CBX_DEINT_METHOD            1524
#define IDC_CHB_X264_ME_INTER_BSUB16x16 1524
#define IDC_PLC_DEINT                   1525
#define IDC_LBL_X264_MV_RANGE           1525
#define IDC_LBL_KERNELDEINT_THRESHOLD   1526
#define IDC_ED_X264_MV_RANGE            1526
#define IDC_TBR_KERNELDEINT_THRESHOLD   1527
#define IDC_CHB_X264_CHROMA_ME          1527
#define IDC_CBX_RAW_FOURCC              1528
#define IDC_LBL_X264_ME_RANGE           1528
#define IDC_CHB_KERNELDEINT_SHARP       1528
#define IDC_LBL_RAW_FOURCC              1529
#define IDC_CHB_KERNELDEINT_TWOWAY      1529
#define IDC_ED_X264_ME_RANGE            1529
#define IDC_CHB_THEO_HQ                 1530
#define IDC_CHB_KERNELDEINT_MAP         1530
#define IDC_CHB_OUTPUTDEBUG             1531
#define IDC_ED_PATH_FFDSHOW             1531
#define IDC_CHB_DROP_FRAMES             1531
#define IDC_CHB_KERNELDEINT_LINKED      1531
#define IDC_CHB_ERRORBOX                1532
#define IDC_LBL_PATH_FFDSHOW            1532
#define IDC_CHB_OUTPUTDEBUGFILE         1533
#define IDC_BT_PATH_FFDSHOW             1533
#define IDC_ED_OUTPUTDEBUGFILE          1534
#define IDC_LBL_PATH_DSCALER            1534
#define IDC_CHB_POSTPROC_MPLAYER_ACCURATE 1534
#define IDC_BT_OUTPUTDEBUGFILE          1535
#define IDC_BT_PATH_DSCALER             1535
#define IDC_GRP_REMOTE                  1535
#define IDC_ED_PATH_DSCALER             1536
#define IDC_RBT_REMOTE_FFDSHOW          1536
#define IDC_CHB_GRAPH                   1537
#define IDC_RBT_REMOTE_USER             1537
#define IDC_CHB_STATS_PSNR              1538
#define IDC_ED_REMOTE_USER              1538
#define IDC_BMP_GRAPH                   1539
#define IDC_CHB_REMOTE_ACCEPTKEYS       1539
#define IDC_CHB_FONT_AUTOSIZE_VIDEOWINDOW 1539
#define IDC_LBL_GRAPH_MAXKB             1540
#define IDC_RBT_RESIZE_MODE_MULT        1540
#define IDC_LBL_STATS_NUMFRAMES         1541
#define IDC_ED_RESIZE_MULT              1541
#define IDC_LBL_STATS_KBPS              1542
#define IDC_LBL_LOGOAWAY_X              1542
#define IDC_LBL_ERROR_RECOGNITION       1542
#define IDC_ED_RESIZE_MOD_16            1542
#define IDC_LBL_STATS_FPS               1543
#define IDC_ED_LOGOAWAY_X               1543
#define IDC_CBX_ERROR_RECOGNITION       1543
#define IDC_RBT_RESIZE_MODE_MULT2       1543
#define IDC_LBL_STATS_PSNR              1544
#define IDC_LBL_LOGOAWAY_Y              1544
#define IDC_LBL_ERROR_CONCEALMENT       1544
#define IDC_LBL_STATS_AVGQUANT          1545
#define IDC_ED_LOGOAWAY_Y               1545
#define IDC_CBX_ERROR_CONCEALMENT       1545
#define IDC_CBX_HUFFYUV_CSP             1546
#define IDC_LBL_LOGOAWAY_DX             1546
#define IDC_CBX_HUFFYUV_PRED            1547
#define IDC_ED_LOGOAWAY_DX              1547
#define IDC_CHB_FORCEINCSP              1548
#define IDC_LBL_LOGOAWAY_DY             1548
#define IDC_CBX_INCSP                   1549
#define IDC_ED_LOGOAWAY_DY              1549
#define IDC_CHB_DY_INTERLACED           1550
#define IDC_CBX_LOGOAWAY_MODE           1550
#define IDC_ED_DY_INTERLACED            1551
#define IDC_LBL_LOGOAWAY_MODE           1551
#define IDC_LBL_DY_INTERLACED           1552
#define IDC_CHB_LOGOAWAY                1552
#define IDC_ED_LAVC_NR                  1553
#define IDC_LBL_LOGOAWAY_BLUR           1553
#define IDC_CHB_PROC                    1554
#define IDC_TBR_LOGOAWAY_BLUR           1554
#define IDC_BT_PROC_CONFIG              1555
#define IDC_LBL_LOGOAWAY_XY             1555
#define IDC_CHB_LUMI_MASKING            1556
#define IDC_CHB_LAVC_NR                 1556
#define IDC_TBR_LOGOAWAY_XY             1556
#define IDC_ED_LUMI_MASKING             1557
#define IDC_IMG_LOGOAWAY_SOLIDCOLOR     1557
#define IDC_CHB_TEMPORAL_CPLX_MASKING   1558
#define IDC_LBL_LOGOAWAY_SOLIDCOLOR     1558
#define IDC_ED_TEMPORAL_CPLX_MASKING    1559
#define IDC_LBL_LOGOAWAY_BORDER_PRESETS 1559
#define IDC_CHB_SPATIAL_CPLX_MASKING    1560
#define IDC_CBX_LOGOAWAY_BORDER_PRESETS 1560
#define IDC_ED_SPATIAL_CPLX_MASKING     1561
#define IDC_CBX_LOGOAWAY_POINT_NW       1561
#define IDC_CHB_P_MASKING               1562
#define IDC_LBL_LOGOAWAY_BORDER_ADVANCED 1562
#define IDC_ED_P_MASKING                1563
#define IDC_CBX_LOGOAWAY_POINT_SW       1563
#define IDC_CHB_DARK_MASKING            1564
#define IDC_CBX_LOGOAWAY_POINT_NE       1564
#define IDC_ED_DARK_MASKING             1565
#define IDC_CBX_LOGOAWAY_POINT_SE       1565
#define IDC_CHB_NAQ                     1566
#define IDC_CBX_LOGOAWAY_BORDER_N       1566
#define IDC_LBL_ELIM                    1567
#define IDC_CBX_LOGOAWAY_BORDER_S       1567
#define IDC_CHB_ELIM_LUM                1568
#define IDC_CBX_LOGOAWAY_BORDER_W       1568
#define IDC_LBL_ELIM_LUM                1569
#define IDC_CBX_LOGOAWAY_BORDER_E       1569
#define IDC_ED_ELIM_LUM                 1570
#define IDC_UD_LOGOAWAY_X               1570
#define IDC_CHB_ELIM_LUM_DC             1571
#define IDC_UD_LOGOAWAY_DX              1571
#define IDC_CHB_SUB_SPLIT               1571
#define IDC_CHB_ELIM_CHROM              1572
#define IDC_UD_LOGOAWAY_Y               1572
#define IDC_LBL_NUMTHREADS              1572
#define IDC_CHB_SUB_OVERLAP             1572
#define IDC_LBL_ELIM_CHROM              1573
#define IDC_UD_LOGOAWAY_DY              1573
#define IDC_GRP_SF_OUT                  1573
#define IDC_ED_ELIM_CHROM               1574
#define IDC_CHB_LOGOAWAY_LUMAONLY       1574
#define IDC_CHB_OUT_PCM16               1574
#define IDC_CHB_ELIM_CHROM_DC           1575
#define IDC_CHB_OUT_PCM24               1575
#define IDC_CHB_XVID_MASKING            1576
#define IDC_CHB_OUT_PCM32               1576
#define IDC_CHB_BORDER_MASKING          1576
#define IDC_CHB_XVID_CHROMAOPT          1577
#define IDC_CHB_OUT_FLOAT32             1577
#define IDC_ED_BORDER_MASKING           1577
#define IDC_CHB_4MV                     1578
#define IDC_GRP_FLOATTOINT              1578
#define IDC_CHB_OUT_LPCM                1578
#define IDC_GRP_PREFERRED_SFS           1579
#define IDC_CHB_ME_ITERATIVE            1579
#define IDC_CHB_OUT_LPCM2               1579
#define IDC_CHB_PREFERRED_PCM16         1580
#define IDC_LBL_ME_CMP                  1581
#define IDC_CBX_NOISESHAPING            1581
#define IDC_CBX_ME_CMP                  1582
#define IDC_LBL_NOISESHAPING            1582
#define IDC_CHB_ME_CMP_CHROMA           1583
#define IDC_CHB_DITHERING               1583
#define IDC_LBL_ME_SUB_CMP              1584
#define IDC_TBR_MERIT                   1584
#define IDC_CBX_ME_SUBCMP               1585
#define IDC_CHB_PREFERRED_PCM32         1585
#define IDC_CHB_ME_SUBCMP_CHROMA        1586
#define IDC_CHB_MIXER_NORMALIZE_MATRIX  1586
#define IDC_CHB_PREFERRED_FLOAT32       1586
#define IDC_LBL_MB_CMP                  1587
#define IDC_ED_MIXERMATRIX00            1587
#define IDC_CHB_OUT_AC3                 1587
#define IDC_CBX_MB_CMP                  1588
#define IDC_CHB_MIXER_VOICE_CONTROL     1588
#define IDC_CHB_MB_CMP_CHROMA           1589
#define IDC_ED_MIXERMATRIX01            1589
#define IDC_LBL_DIA_SIZE                1590
#define IDC_ED_MIXERMATRIX02            1590
#define IDC_CBX_DIA_SIZE                1591
#define IDC_ED_MIXERMATRIX03            1591
#define IDC_LBL_ME_LAST_PRED_COUNT      1592
#define IDC_ED_MIXERMATRIX04            1592
#define IDC_ED_ME_LAST_PRED_COUNT       1593
#define IDC_ED_MIXERMATRIX05            1593
#define IDC_LBL_ME_PREPASS              1594
#define IDC_LBL_MIXERMATRIX_L           1594
#define IDC_CBX_ME_PREPASS              1595
#define IDC_LBL_MIXERMATRIX_C           1595
#define IDC_LBL_ME_PRECMP               1596
#define IDC_LBL_MIXERMATRIX_R           1596
#define IDC_CBX_ME_PRECMP               1597
#define IDC_LBL_MIXERMATRIX_SL          1597
#define IDC_CHB_ME_PRECMP_CHROMA        1598
#define IDC_LBL_MIXERMATRIX_SR          1598
#define IDC_LBL_DIA_SIZE_PRE            1599
#define IDC_LBL_MIXERMATRIX_LFE         1599
#define IDC_CBX_DIA_SIZE_PRE            1600
#define IDC_ED_MIXERMATRIX10            1600
#define IDC_LBL_VOLUME_L2               1600
#define IDC_CHB_QPEL                    1601
#define IDC_ED_MIXERMATRIX11            1601
#define IDC_LBL_VOLUME_C2               1601
#define IDC_LBL_ME_SUBQ                 1602
#define IDC_ED_MIXERMATRIX12            1602
#define IDC_LBL_VOLUME_R2               1602
#define IDC_ED_ME_SUBQ                  1603
#define IDC_ED_MIXERMATRIX13            1603
#define IDC_LBL_VOLUME_SL2              1603
#define IDC_LBL_MB_DECISION             1604
#define IDC_ED_MIXERMATRIX14            1604
#define IDC_LBL_VOLUME_SR2              1604
#define IDC_CBX_MB_DECISION             1605
#define IDC_ED_MIXERMATRIX15            1605
#define IDC_LBL_VOLUME_LFE2             1605
#define IDC_CHB_MV0                     1606
#define IDC_ED_MIXERMATRIX20            1606
#define IDC_CHB_CBP_RD                  1607
#define IDC_ED_MIXERMATRIX21            1607
#define IDC_ED_MIXERMATRIX22            1608
#define IDC_ED_MIXERMATRIX23            1609
#define IDC_ED_MIXERMATRIX24            1610
#define IDC_ED_MIXERMATRIX25            1611
#define IDC_ED_MIXERMATRIX30            1612
#define IDC_CHB_GMC                     1613
#define IDC_ED_MIXERMATRIX31            1613
#define IDC_CHB_XVID_CHROMA_ME          1614
#define IDC_ED_MIXERMATRIX32            1614
#define IDC_CHB_XVID_ME_PRESET          1615
#define IDC_ED_MIXERMATRIX33            1615
#define IDC_CBX_ME_XVID                 1616
#define IDC_ED_MIXERMATRIX34            1616
#define IDC_CHB_XVIDME_ADVANCEDDIAMOND8 1617
#define IDC_ED_MIXERMATRIX35            1617
#define IDC_CHB_XVIDME_ADVANCEDDIAMOND16 1618
#define IDC_ED_MIXERMATRIX40            1618
#define IDC_CHB_XVIDME_HALFPELREFINE8   1619
#define IDC_ED_MIXERMATRIX41            1619
#define IDC_CHB_XVIDME_HALFPELREFINE16  1620
#define IDC_ED_MIXERMATRIX42            1620
#define IDC_CHB_XVIDME_EXTSEARCH8       1621
#define IDC_ED_MIXERMATRIX43            1621
#define IDC_CHB_XVIDME_EXTSEARCH16      1622
#define IDC_ED_MIXERMATRIX44            1622
#define IDC_CHB_XVIDME_USESQUARES8      1623
#define IDC_ED_MIXERMATRIX45            1623
#define IDC_CHB_XVIDME_USESQUARES16     1624
#define IDC_ED_MIXERMATRIX50            1624
#define IDC_CHB_XVIDME_INTER4V          1625
#define IDC_ED_MIXERMATRIX51            1625
#define IDC_CHB_XVID_VHQ_PRESET         1626
#define IDC_ED_MIXERMATRIX52            1626
#define IDC_CBX_VHQ_XVID                1627
#define IDC_ED_MIXERMATRIX53            1627
#define IDC_CHB_XVIDVHQ_MODEDECISION_BITS 1628
#define IDC_ED_MIXERMATRIX54            1628
#define IDC_CHB_XVIDVHQ_HALFPELREFINE8_BITS 1629
#define IDC_ED_MIXERMATRIX55            1629
#define IDC_CHB_XVIDVHQ_HALFPELREFINE16_BITS 1630
#define IDC_LBL_MIXERMATRIX_L1          1630
#define IDC_CHB_XVIDVHQ_QUARTERPELREFINE8_BITS 1631
#define IDC_LBL_MIXERMATRIX_C1          1631
#define IDC_CHB_XVIDVHQ_QUARTERPELREFINE16_BITS 1632
#define IDC_LBL_MIXERMATRIX_SL1         1632
#define IDC_CHB_XVIDVHQ_EXTSEARCH_BITS  1633
#define IDC_LBL_MIXERMATRIX_SR1         1633
#define IDC_CHB_XVIDVHQ_CHECKPREDICTION_BITS 1634
#define IDC_LBL_MIXERMATRIX_LFE1        1634
#define IDC_LBL_VRATETOL                1635
#define IDC_LBL_MIXERMATRIX_R1          1635
#define IDC_ED_VRATETOL                 1636
#define IDC_CHB_MIXER_CUSTOM            1636
#define IDC_LBL_VQCOMP                  1637
#define IDC_CHB_MIXER_EXPAND_STEREO     1637
#define IDC_LBL_VOLUME_NORMALIZE_MAX    1637
#define IDC_ED_VQCOMP                   1638
#define IDC_ED_VOLUME_NORMALIZE_MAX     1638
#define IDC_LBL_VQBLUR1                 1639
#define IDC_LBL_VOLUME_NORMALIZE_MAX2   1639
#define IDC_ED_VQBLUR1                  1640
#define IDC_LBL_VQBLUR2                 1641
#define IDC_LBL_VOLUME_NORMALIZE_CURRENT 1641
#define IDC_ED_VQBLUR2                  1642
#define IDC_TBR_VOLUME_L                1642
#define IDC_LBL_VQDIFF                  1643
#define IDC_TBR_VOLUME_C                1643
#define IDC_ED_VQDIFF                   1644
#define IDC_TBR_VOLUME_R                1644
#define IDC_CHB_RC_SQUISH               1645
#define IDC_TBR_VOLUME_SL               1645
#define IDC_ED_XVID_REACTION_DELAY_FACTOR 1646
#define IDC_LBL_MIN_BITRATE             1646
#define IDC_TBR_VOLUME_SR               1646
#define IDC_ED_XVID_AVERAGING_PERIOD    1647
#define IDC_ED_MIN_BITRATE              1647
#define IDC_TBR_VOLUME_LFE              1647
#define IDC_ED_XVID_BUFFER              1648
#define IDC_LBL_MAX_BITRATE             1648
#define IDC_LBL_VOLUME_L                1648
#define IDC_LBL_BR_INFO                 1649
#define IDC_LBL_VOLUME_C                1649
#define IDC_CBX_BR_FPS                  1650
#define IDC_LBL_BUFFER_SIZE             1650
#define IDC_LBL_VOLUME_R                1650
#define IDC_LBL_BR_TIME                 1651
#define IDC_ED_BUFFER_SIZE              1651
#define IDC_LBL_VOLUME_SL               1651
#define IDC_ED_BR_LEN                   1652
#define IDC_LBL_VOLUME_SR               1652
#define IDC_LBL_BR_BPS                  1653
#define IDC_LBL_VOLUME_LFE              1653
#define IDC_CHB_STORE_AVI               1654
#define IDC_ED_DOLBYDECODER_DELAY       1654
#define IDC_CHB_STORE_EXTERNAL          1655
#define IDC_LBL_DOLBYDECODER_DELAY2     1655
#define IDC_CBX_MUXER                   1656
#define IDC_LBL_DOLBYDECODER_DELAY3     1656
#define IDC_ED_STORE_EXTERNAL           1657
#define IDC_CHB_DOLBYDECODER            1657
#define IDC_BT_STORE_EXTERNAL           1658
#define IDC_LBL_DELAY_L                 1658
#define IDC_LBL_LAVC_STATS              1659
#define IDC_ED_DELAY_L                  1659
#define IDC_RBT_LAVC_STATS_NONE         1660
#define IDC_LBL_DELAY_L2                1660
#define IDC_RBT_LAVC_STATS_WRITE        1661
#define IDC_ED_DELAY_C                  1661
#define IDC_RBT_LAVC_STATS_READ         1662
#define IDC_LBL_DELAY_C2                1662
#define IDC_RBT_LAVC_STATS_RW           1663
#define IDC_LBL_DELAY_C                 1663
#define IDC_BT_BITRATE                  1664
#define IDC_ED_DELAY_R                  1664
#define IDC_ED_LAVC_STATS               1665
#define IDC_LBL_DELAY_R2                1665
#define IDC_BT_LAVC_STATS               1666
#define IDC_LBL_DELAY_R                 1666
#define IDC_CHB_FPS                     1667
#define IDC_ED_DELAY_SL                 1667
#define IDC_LBL_DELAY_SL2               1668
#define IDC_LBL_DELAY_SL                1669
#define IDC_ED_ASPECTX                  1670
#define IDC_ED_DELAY_SR                 1670
#define IDC_LBL_CHANNELSWAP_REAR        1670
#define IDC_LBL_ASPECT                  1671
#define IDC_LBL_DELAY_SR2               1671
#define IDC_LBL_CHANNELSWAP_REAR2       1671
#define IDC_ED_ASPECTY                  1672
#define IDC_LBL_DELAY_SR                1672
#define IDC_BT_ASPECT                   1673
#define IDC_ED_DELAY_LFE                1673
#define IDC_CBX_QUANT_TYPE              1674
#define IDC_LBL_DELAY_LFE2              1674
#define IDC_ED_FPS_NUM                  1674
#define IDC_LBL_Q_I                     1675
#define IDC_LBL_DELAY_LFE               1675
#define IDC_LBL_ASPECT2                 1675
#define IDC_LBL_Q_P                     1676
#define IDC_CHB_DELAY                   1676
#define IDC_ED_FPS_DEN                  1676
#define IDC_LBL_Q_B                     1677
#define IDC_PBR_VOLUME_L                1677
#define IDC_BT_FPS                      1677
#define IDC_LBL_Q_MB                    1678
#define IDC_PBR_VOLUME_C                1678
#define IDC_ED_Q_I_MIN                  1679
#define IDC_PBR_VOLUME_R                1679
#define IDC_ED_Q_P_MIN                  1680
#define IDC_PBR_VOLUME_SL               1680
#define IDC_ED_Q_B_MIN                  1681
#define IDC_PBR_VOLUME_SR               1681
#define IDC_ED_Q_MB_MIN                 1682
#define IDC_PBR_VOLUME_LFE              1682
#define IDC_ED_Q_I_MAX                  1683
#define IDC_CHB_VOLUME_SHOWCURRENT      1683
#define IDC_CHB_FIR_SHOWFFT             1683
#define IDC_CHB_AUDIOSWITCHER           1683
#define IDC_CHB_SUB_STEREOSCOPIC        1683
#define IDC_ED_Q_P_MAX                  1684
#define IDC_TBR_HEADPHONE_DIM           1684
#define IDC_ED_Q_B_MAX                  1685
#define IDC_LBL_HEADPHONE_DIM           1685
#define IDC_ED_Q_MB_MAX                 1686
#define IDC_CHB_FIR                     1686
#define IDC_TBR_MIXER_CLEV              1686
#define IDC_LBL_I_QUANTFACTOR           1687
#define IDC_BMP_FIR                     1687
#define IDC_TBR_MIXER_SLEV              1687
#define IDC_ED_I_QUANTFACTOR            1688
#define IDC_LBL_FIR_TAPS                1688
#define IDC_TBR_MIXER_LFELEV            1688
#define IDC_LBL_I_QUANTOFFSET           1689
#define IDC_ED_FIR_TAPS                 1689
#define IDC_ED_I_QUANTOFFSET            1690
#define IDC_LBL_FIR_TYPE                1690
#define IDC_LBL_B_QUANTFACTOR           1691
#define IDC_CBX_FIR_TYPE                1691
#define IDC_ED_B_QUANTFACTOR            1692
#define IDC_LBL_FIR_WINDOW              1692
#define IDC_LBL_B_QUANTOFFSET           1693
#define IDC_CBX_FIR_WINDOW              1693
#define IDC_ED_B_QUANTOFFSET            1694
#define IDC_LBL_FIR_KAISER_BETA         1694
#define IDC_CHB_QUANT_INTER_BIAS        1695
#define IDC_ED_FIR_KAISER_BETA          1695
#define IDC_ED_QUANT_INTER_BIAS         1696
#define IDC_LBL_FIR_FREQ                1696
#define IDC_CHB_QUANT_INTRA_BIAS        1697
#define IDC_ED_FIR_FREQ                 1697
#define IDC_ED_QUANT_INTRA_BIAS         1698
#define IDC_LBL_FIR_WIDTH               1698
#define IDC_CHB_TRELLIS_QUANT           1699
#define IDC_ED_FIR_WIDTH                1699
#define IDC_LBL_DCT_ALGO                1700
#define IDC_CHB_FIR_MAXFREQ             1700
#define IDC_CBX_DCT_ALGO                1701
#define IDC_ED_FIR_MAXFREQ              1701
#define IDC_LBL_MIXER_CLEV              1701
#define IDC_LBL_MIXER_SLEV              1702
#define IDC_LBL_QNS                     1703
#define IDC_LBL_MIXER_LFELEV            1703
#define IDC_CBX_QNS                     1704
#define IDC_LBL_MIXER_CLEV2             1704
#define IDC_LBL_AUDIODENOISE_THRESHOLD  1704
#define IDC_LBL_MIXER_SLEV2             1705
#define IDC_TBR_AUDIODENOISE_THRESHOLD  1705
#define IDC_LBL_MIXER_LFELEV2           1706
#define IDC_CHB_AUDIODENOISE            1706
#define IDC_LBL_QUANT_DCPRECISION       1707
#define IDC_LBL_LEVELS_MODE             1707
#define IDC_CBX_QUANT_DCPRECISION       1708
#define IDC_CBX_LEVELS_MODE             1708
#define IDC_CBX_AUDIOSWITCHER           1708
#define IDC_CBX_VOBSUB_DEFLANG          1708
#define IDC_ED_QUANT_TABLE_INTRA1       1709
#define IDC_GRP_AUDIOSWITCHER           1709
#define IDC_CBX_VOBSUB_AA               1709
#define IDC_ED_QUANT_TABLE_INTRA12      1710
#define IDC_LBL_AUDIOSWITCHER           1710
#define IDC_CBX_VOBSUB_CURLANG          1710
#define IDC_ED_QUANT_TABLE_INTRA13      1711
#define IDC_CHB_CRYSTALITY              1711
#define IDC_CBX_VOBSUB_DEFLANG2         1711
#define IDC_ED_QUANT_TABLE_INTRA14      1712
#define IDC_LBL_CRYSTALITY_BEXT_LEVEL   1712
#define IDC_ED_QUANT_TABLE_INTRA15      1713
#define IDC_TBR_CRYSTALITY_BEXT_LEVEL   1713
#define IDC_ED_QUANT_TABLE_INTRA16      1714
#define IDC_LBL_CRYSTALITY_FILTER_LEVEL 1714
#define IDC_ED_QUANT_TABLE_INTRA17      1715
#define IDC_TBR_CRYSTALITY_FILTER_LEVEL 1715
#define IDC_ED_QUANT_TABLE_INTRA18      1716
#define IDC_LBL_CRYSTALITY_HARMONICS_LEVEL 1716
#define IDC_ED_QUANT_TABLE_INTRA19      1717
#define IDC_TBR_CRYSTALITY_HARMONICS_LEVEL 1717
#define IDC_ED_QUANT_TABLE_INTRA20      1718
#define IDC_LBL_CRYSTALITY_ECHO_LEVEL   1718
#define IDC_ED_QUANT_TABLE_INTRA21      1719
#define IDC_TBR_CRYSTALITY_ECHO_LEVEL   1719
#define IDC_ED_QUANT_TABLE_INTRA22      1720
#define IDC_LBL_CRYSTALITY_FEEDBACK_LEVEL 1720
#define IDC_ED_QUANT_TABLE_INTRA23      1721
#define IDC_TBR_CRYSTALITY_FEEDBACK_LEVEL 1721
#define IDC_ED_QUANT_TABLE_INTRA24      1722
#define IDC_LBL_CRYSTALITY_STEREO_LEVEL 1722
#define IDC_LBL_SUB_STEREOSCOPICPAR     1722
#define IDC_ED_QUANT_TABLE_INTRA25      1723
#define IDC_TBR_CRYSTALITY_STEREO_LEVEL 1723
#define IDC_BT_RESETORDER               1723
#define IDC_LBL_SUB_LINESPACING         1723
#define IDC_ED_QUANT_TABLE_INTRA26      1724
#define IDC_GRP_VOBSUB                  1724
#define IDC_ED_QUANT_TABLE_INTRA27      1725
#define IDC_CHB_VOBSUB                  1725
#define IDC_ED_QUANT_TABLE_INTRA28      1726
#define IDC_LBL_VOBSUB_DEFLANG          1726
#define IDC_ED_QUANT_TABLE_INTRA29      1727
#define IDC_LBL_VOBSUB_AA               1727
#define IDC_CHB_DGBOB_AP                1727
#define IDC_ED_QUANT_TABLE_INTRA30      1728
#define IDC_LBL_VOBSUB_CURLANG          1728
#define IDC_LBL_DGBOB_MODE              1728
#define IDC_ED_QUANT_TABLE_INTRA31      1729
#define IDC_CBX_DGBOB_MODE              1729
#define IDC_LBL_VOBSUB_SCALE            1729
#define IDC_ED_QUANT_TABLE_INTRA32      1730
#define IDC_LBL_DGBOB_THRESHOLD         1730
#define IDC_LBL_VOBSUB_GAUSS            1730
#define IDC_ED_QUANT_TABLE_INTRA33      1731
#define IDC_TBR_DGBOB_THRESHOLD         1731
#define IDC_ED_QUANT_TABLE_INTRA34      1732
#define IDC_ED_QUANT_TABLE_INTRA35      1733
#define IDC_CHB_LFECROSSOVER            1733
#define IDC_ED_QUANT_TABLE_INTRA36      1734
#define IDC_LBL_LFECROSSOVER_FREQ       1734
#define IDC_ED_QUANT_TABLE_INTRA37      1735
#define IDC_TBR_LFECROSSOVER_FREQ       1735
#define IDC_ED_QUANT_TABLE_INTRA38      1736
#define IDC_LBL_LFECROSSOVER_GAIN       1736
#define IDC_ED_QUANT_TABLE_INTRA39      1737
#define IDC_TBR_LFECROSSOVER_GAIN       1737
#define IDC_ED_QUANT_TABLE_INTRA40      1738
#define IDC_CHB_ADDTOROT                1738
#define IDC_ED_QUANT_TABLE_INTRA41      1739
#define IDC_ED_QUANT_TABLE_INTRA42      1740
#define IDC_LBL_GRAB_STEP               1740
#define IDC_ED_QUANT_TABLE_INTRA43      1741
#define IDC_LBL_GRAB_STEP2              1741
#define IDC_CHB_LFECROSSOVER_LRCUT      1741
#define IDC_ED_QUANT_TABLE_INTRA44      1742
#define IDC_CBX_OUT_AC3                 1742
#define IDC_ED_QUANT_TABLE_INTRA45      1743
#define IDC_LBL_OUT_AC3                 1743
#define IDC_ED_QUANT_TABLE_INTRA46      1744
#define IDC_LBL_CHANNELSWAP_LFE         1744
#define IDC_ED_QUANT_TABLE_INTRA47      1745
#define IDC_LBL_CHANNELSWAP_SR          1745
#define IDC_ED_QUANT_TABLE_INTRA48      1746
#define IDC_LBL_CHANNELSWAP_SL          1746
#define IDC_ED_QUANT_TABLE_INTRA49      1747
#define IDC_LBL_CHANNELSWAP_R           1747
#define IDC_ED_QUANT_TABLE_INTRA50      1748
#define IDC_LBL_CHANNELSWAP_C           1748
#define IDC_ED_QUANT_TABLE_INTRA51      1749
#define IDC_LBL_CHANNELSWAP_L           1749
#define IDC_ED_QUANT_TABLE_INTRA52      1750
#define IDC_CBX_CHANNELSWAP_L           1750
#define IDC_ED_QUANT_TABLE_INTRA53      1751
#define IDC_LBL_CHANNELSWAP_L2          1751
#define IDC_ED_QUANT_TABLE_INTRA54      1752
#define IDC_CBX_CHANNELSWAP_C           1752
#define IDC_ED_QUANT_TABLE_INTRA55      1753
#define IDC_CBX_CHANNELSWAP_R           1753
#define IDC_ED_QUANT_TABLE_INTRA56      1754
#define IDC_CBX_CHANNELSWAP_SL          1754
#define IDC_ED_QUANT_TABLE_INTRA57      1755
#define IDC_CBX_CHANNELSWAP_REAR        1755
#define IDC_ED_QUANT_TABLE_INTRA58      1756
#define IDC_CBX_CHANNELSWAP_SR          1756
#define IDC_ED_QUANT_TABLE_INTRA59      1757
#define IDC_CBX_CHANNELSWAP_LFE         1757
#define IDC_ED_QUANT_TABLE_INTRA60      1758
#define IDC_LBL_CHANNELSWAP_C2          1758
#define IDC_ED_QUANT_TABLE_INTRA61      1759
#define IDC_LBL_CHANNELSWAP_R2          1759
#define IDC_ED_QUANT_TABLE_INTRA62      1760
#define IDC_LBL_CHANNELSWAP_SL2         1760
#define IDC_ED_QUANT_TABLE_INTRA63      1761
#define IDC_LBL_CHANNELSWAP_SR2         1761
#define IDC_ED_QUANT_TABLE_INTRA64      1762
#define IDC_LBL_CHANNELSWAP_LFE2        1762
#define IDC_LBL_QUANT_TABLE_INTER       1763
#define IDC_CHB_CHANNELSWAP             1763
#define IDC_ED_QUANT_TABLE_INTER1       1764
#define IDC_CHB_VIDEODELAYEND           1764
#define IDC_ED_QUANT_TABLE_INTER2       1765
#define IDC_LBL_VIDEODELAYSTART         1765
#define IDC_ED_QUANT_TABLE_INTER3       1766
#define IDC_ED_QUANT_TABLE_INTER4       1767
#define IDC_CHB_SUB_MINDURATION         1767
#define IDC_ED_QUANT_TABLE_INTER5       1768
#define IDC_CBX_SUB_MINDURATION         1768
#define IDC_ED_QUANT_TABLE_INTER6       1769
#define IDC_ED_QUANT_TABLE_INTER7       1770
#define IDC_ED_QUANT_TABLE_INTER8       1771
#define IDC_ED_SUB_MINDURATION          1771
#define IDC_ED_QUANT_TABLE_INTER9       1772
#define IDC_LBL_SUB_MINDURATION         1772
#define IDC_ED_QUANT_TABLE_INTER10      1773
#define IDC_LBL_SUB_MINDURATION2        1773
#define IDC_ED_QUANT_TABLE_INTER11      1774
#define IDC_LBL_OSD_POSX                1774
#define IDC_ED_SUB_SPLIT_BORDER         1774
#define IDC_ED_QUANT_TABLE_INTER12      1775
#define IDC_TBR_OSD_POSX                1775
#define IDC_LBL_SUB_SPLIT_BORDER2       1775
#define IDC_ED_QUANT_TABLE_INTER13      1776
#define IDC_LBL_OSD_POSY                1776
#define IDC_ED_QUANT_TABLE_INTER14      1777
#define IDC_TBR_OSD_POSY                1777
#define IDC_ED_QUANT_TABLE_INTER15      1778
#define IDC_CBX_X264_ME_SUBPELREFINEMENT 1778
#define IDC_ED_QUANT_TABLE_INTER16      1779
#define IDC_LBL_X264_ME_SUBPELREFINEMENT 1779
#define IDC_ED_QUANT_TABLE_INTER17      1780
#define IDC_IMG_COLORIZE                1780
#define IDC_LBL_X264_ME_PREDICTION      1780
#define IDC_ED_QUANT_TABLE_INTER18      1781
#define IDC_LBL_COLORIZE                1781
#define IDC_CBX_X264_ME_PREDICTION      1781
#define IDC_ED_QUANT_TABLE_INTER19      1782
#define IDC_LBL_COLORIZESTRENGTH        1782
#define IDC_LBL_X264_ME_METHOD          1782
#define IDC_ED_QUANT_TABLE_INTER20      1783
#define IDC_CBX_X264_ME_METHOD          1783
#define IDC_ED_QUANT_TABLE_INTER21      1784
#define IDC_ED_QUANT_TABLE_INTER22      1785
#define IDC_TBR_FLICKER_A               1785
#define IDC_ED_QUANT_TABLE_INTER23      1786
#define IDC_TBR_FLICKER_F               1786
#define IDC_ED_QUANT_TABLE_INTER24      1787
#define IDC_TBR_SHAKE_A                 1787
#define IDC_CHB_COLORIZE_CHROMAONLY     1787
#define IDC_CHB_SUBTEXTPIN              1787
#define IDC_CHB_SUBFIX_AP               1787
#define IDC_ED_QUANT_TABLE_INTER25      1788
#define IDC_TBR_SHAKE_F                 1788
#define IDC_CHB_SUBFIX_IL               1788
#define IDC_CHB_SUBCC                   1788
#define IDC_ED_QUANT_TABLE_INTER26      1789
#define IDC_TBR_LINES_F                 1789
#define IDC_CBX_SUBFIX_IL               1789
#define IDC_CHB_SUBTEXTPIN_SSA          1789
#define IDC_ED_QUANT_TABLE_INTER27      1790
#define IDC_TBR_LINES_A                 1790
#define IDC_CHB_SUBFIX_PUNCTUATION      1790
#define IDC_CHB_SUBEXTENDEDTAGS         1790
#define IDC_ED_QUANT_TABLE_INTER28      1791
#define IDC_TBR_LINES_TRANSPARENCY      1791
#define IDC_CHB_SUBFIX_CAPITAL          1791
#define IDC_ED_QUANT_TABLE_INTER29      1792
#define IDC_TBR_SCRATCHES_F             1792
#define IDC_CHB_SUBFIX_NUMBERS          1792
#define IDC_ED_QUANT_TABLE_INTER30      1793
#define IDC_TBR_SCRATCHES_A             1793
#define IDC_GRP_SUBTITLESTEXT           1793
#define IDC_ED_QUANT_TABLE_INTER31      1794
#define IDC_TBR_SCRATCHES_TRANSPARENCY  1794
#define IDC_LBL_SUBFIX                  1794
#define IDC_ED_QUANT_TABLE_INTER32      1795
#define IDC_CHB_SUBFIX_ORTOGRAPHY       1795
#define IDC_TBR_LINES_C                 1795
#define IDC_ED_QUANT_TABLE_INTER33      1796
#define IDC_CBX_SUBFIX_ORTOGRAPHY       1796
#define IDC_CHB_VOBSUB_CHANGEPOSITION   1796
#define IDC_TBR_SCRATCHES_C             1796
#define IDC_ED_QUANT_TABLE_INTER34      1797
#define IDC_TBR_VOBSUB_SCALE            1797
#define IDC_ED_QUANT_TABLE_INTER35      1798
#define IDC_CHB_BITMAP                  1798
#define IDC_TBR_VOBSUB_GAUSS            1798
#define IDC_CHB_SUBFIX_HEARING          1798
#define IDC_ED_QUANT_TABLE_INTER36      1799
#define IDC_LBL_BITMAP_FLNM             1799
#define IDC_ED_QUANT_TABLE_INTER37      1800
#define IDC_ED_BITMAP_FLNM              1800
#define IDC_ED_QUANT_TABLE_INTER38      1801
#define IDC_BT_BITMAP_FLNM              1801
#define IDC_ED_QUANT_TABLE_INTER39      1802
#define IDC_LBL_BITMAP_POSX             1802
#define IDC_ED_QUANT_TABLE_INTER40      1803
#define IDC_LBL_BITMAP_POSY             1803
#define IDC_ED_QUANT_TABLE_INTER41      1804
#define IDC_TBR_BITMAP_POSX             1804
#define IDC_ED_QUANT_TABLE_INTER42      1805
#define IDC_TBR_BITMAP_POSY             1805
#define IDC_ED_QUANT_TABLE_INTER43      1806
#define IDC_CBX_BITMAP_ALIGN            1806
#define IDC_ED_QUANT_TABLE_INTER44      1807
#define IDC_LBL_BITMAP_OPACITY          1807
#define IDC_ED_QUANT_TABLE_INTER45      1808
#define IDC_TBR_BITMAP_OPACITY          1808
#define IDC_ED_QUANT_TABLE_INTER46      1809
#define IDC_CBX_BITMAP_MODE             1809
#define IDC_ED_QUANT_TABLE_INTER47      1810
#define IDC_LBL_BITMAP_ALIGN            1810
#define IDC_ED_QUANT_TABLE_INTER48      1811
#define IDC_CHB_ALWAYEXTENSIBLE         1811
#define IDC_ED_QUANT_TABLE_INTER49      1812
#define IDC_ED_QUANT_TABLE_INTER50      1813
#define IDC_CHB_ALLOWOUTSTREAM          1813
#define IDC_ED_QUANT_TABLE_INTER51      1814
#define IDC_BT_EQ_PRESET_LOAD           1814
#define IDC_ED_QUANT_TABLE_INTER52      1815
#define IDC_ED_QUANT_TABLE_INTER53      1816
#define IDC_ED_EQ0                      1816
#define IDC_ED_QUANT_TABLE_INTER54      1817
#define IDC_ED_EQ1                      1817
#define IDC_ED_QUANT_TABLE_INTER55      1818
#define IDC_ED_EQ2                      1818
#define IDC_ED_QUANT_TABLE_INTER56      1819
#define IDC_ED_EQ3                      1819
#define IDC_ED_QUANT_TABLE_INTER57      1820
#define IDC_ED_EQ4                      1820
#define IDC_ED_QUANT_TABLE_INTER58      1821
#define IDC_ED_EQ5                      1821
#define IDC_ED_QUANT_TABLE_INTER59      1822
#define IDC_ED_EQ6                      1822
#define IDC_ED_QUANT_TABLE_INTER60      1823
#define IDC_ED_EQ7                      1823
#define IDC_ED_QUANT_TABLE_INTER61      1824
#define IDC_ED_EQ8                      1824
#define IDC_ED_QUANT_TABLE_INTER62      1825
#define IDC_ED_EQ9                      1825
#define IDC_ED_QUANT_TABLE_INTER63      1826
#define IDC_CHB_EQ_SUPER                1826
#define IDC_ED_QUANT_TABLE_INTER64      1827
#define IDC_CHB_FONT_FAST               1827
#define IDC_LBL_X264_DEBLOCK_ALPHA      1827
#define IDC_BT_QUANT_TABLE_LOAD         1828
#define IDC_CBX_ASPECT                  1828
#define IDC_ED_X264_DEBLOCK_ALPHA       1828
#define IDC_BT_QUANT_TABLE_SAVE         1829
#define IDC_BT_REMOTE_GIRDER            1829
#define IDC_LBL_X264_DEBLOCK_BETA       1829
#define IDC_ED_QUANT_TABLE_INTRA2       1830
#define IDC_CHB_PICTPROP_LEVELFIX_LUMA  1830
#define IDC_ED_X264_DEBLOCK_BETA        1830
#define IDC_ED_QUANT_TABLE_INTRA3       1831
#define IDC_CHB_PICTPROP_LEVELFIX_LUMA_FULL 1831
#define IDC_ED_QUANT_TABLE_INTRA4       1832
#define IDC_GRP_ALLOW_SIMD              1832
#define IDC_ED_QUANT_TABLE_INTRA5       1833
#define IDC_ED_QUANT_TABLE_INTRA6       1834
#define IDC_LV_PROPS                    1834
#define IDC_ED_QUANT_TABLE_INTRA7       1835
#define IDC_BT_EXPORT                   1835
#define IDC_ED_QUANT_TABLE_INTRA8       1836
#define IDC_BT_DONATE                   1836
#define IDC_LBL_SUB_SPLIT_BORDER        1836
#define IDC_ED_QUANT_TABLE_INTRA9       1837
#define IDC_CHB_SUB_SEARCHHEURISTIC     1837
#define IDC_CHB_CODEC_OPT1              1837
#define IDC_ED_QUANT_TABLE_INTRA10      1838
#define IDC_CHB_CODEC_OPT2              1838
#define IDC_ED_QUANT_TABLE_INTRA11      1839
#define IDC_BT_FFDSHOWVERSION           1839
#define IDC_LBL_QUANT_TABLE_INTRA       1840
#define IDC_LBL_THEO_SHARPNESS          1840
#define IDC_CBX_THEO_SHARPNESS          1841
#define IDC_CHB_XVID2PASS_USE_WRITE     1842
#define IDC_LBL_THEO_NOISESENSITIVITY   1842
#define IDC_TBR_THEO_NOISESENSITIVITY   1843
#define IDC_LBL_STATS2                  1844
#define IDC_CBX_AOUT_CONNECTTO          1844
#define IDC_LBL_X264_AQ_STRENGTH        1844
#define IDC_ED_STATS2                   1845
#define IDC_CHB_AOUT_CONNECTTO          1845
#define IDC_TBR_X264_AQ_STRENGTH        1845
#define IDC_BT_STATS2                   1846
#define IDC_CHB_AOUT_CONNECTTO_SPDIF    1846
#define IDC_BT_SECOND_SIMULATE          1847
#define IDC_GRP_AOUT_OTHER              1847
#define IDC_ED_MAX_BITRATE              1848
#define IDC_ED_MAX_OVERFLOW_IMPR        1849
#define IDC_CHB_LICENSE                 1849
#define IDC_ED_MAX_OVERFLOW_DEGR        1850
#define IDC_ED_KFBOOST                  1851
#define IDC_ED_KFTRESHOLD               1852
#define IDC_TAB                         1852
#define IDC_ED_KFREDUCTION              1853
#define IDC_GRP_AVISYNTH                1853
#define IDC_BT_PERFECT_ANALYZE          1854
#define IDC_LBL_LOGOAWAY_PARAMBITMAP    1854
#define IDC_BT_PERFECT_SIMULATE         1855
#define IDC_ED_LOGOAWAY_PARAMBITMAP     1855
#define IDC_BMP_PERFECT_GRAPH           1856
#define IDC_BT_LOGOAWAY_PARAMBITMAP     1856
#define IDC_LBL_PERFECT_AVGMIN          1857
#define IDC_GRP_RESIZE_BORDERS          1857
#define IDC_LBL_PERFECT_AVGMAX          1858
#define IDC_RBT_BORDER_PERCENT          1858
#define IDC_BMP_PERFECT_QUANT_PERCENTS  1859
#define IDC_RBT_BORDER_PIXELS           1859
#define IDC_BMP_PERFECT_QUANT_CNT       1860
#define IDC_RBT_BORDER_INSIDE           1860
#define IDC_LBL_PERFECT_BYTES           1861
#define IDC_RBT_BORDER_OUTSIDE          1861
#define IDC_LBL_PERFECT_NUMFRAMES       1862
#define IDC_LBL_BORDER_HORIZ            1862
#define IDC_LBL_PERFECT_BITRATE         1863
#define IDC_LBL_BORDER_VERT             1863
#define IDC_LBL_PERFECT_AVGFRAMESIZE    1864
#define IDC_LBL_BORDER_HORIZ_PERCENT    1864
#define IDC_LBL_PERFECT_AVGQUANT        1865
#define IDC_LBL_BORDER_HORIZ_PIXELS     1865
#define IDC_CHB_WMV9_ASFOUT             1866
#define IDC_LBL_BORDER_VERT_PIXELS      1866
#define IDC_ED_WMV9_KFSECS              1867
#define IDC_LBL_BORDER_VERT_PERCENT     1867
#define IDC_LBL_WMV9_CPLX               1868
#define IDC_TBR_BORDER_VERT_PERCENT     1868
#define IDC_ED_WMV9_CPLX                1869
#define IDC_TBR_BORDER_HORIZ_PERCENT    1869
#define IDC_LBL_WMV9_CRISP              1870
#define IDC_ED_SUBTITLES_EXPAND_X       1870
#define IDC_ED_WMV9_CRISP               1871
#define IDC_ED_SUBTITLES_EXPAND_Y       1871
#define IDC_CHB_WMV9_DEINT              1872
#define IDC_LBL_SUBTITLES_EXPAND2       1872
#define IDC_CHB_WMV9_IVTC               1873
#define IDC_BT_SUBTITLES_EXPAND         1874
#define IDC_RBT_RESAMPLE_ALWAYS         1875
#define IDC_RBT_RESAMPLE_IF             1876
#define IDC_LV_PRESETENC                1877
#define IDC_BT_RESAMPLE_COND            1877
#define IDC_CHB_BLUR_DENOISE3D          1878
#define IDC_ED_RESAMPLE_CONDFREQ        1878
#define IDC_BT_RESAMPLE_CONDFREQ        1879
#define IDC_CHB_CONVOLVER               1880
#define IDC_LBL_CONVOLVER_FILE          1881
#define IDC_BT_RESAMPLE_FREQ            1881
#define IDC_ED_CONVOLVER_FILE           1883
#define IDC_BT_CONVOLVER_FILE           1884
#define IDC_CHB_B_PYRAMID               1885
#define IDC_LBL_PROPS_ITALIC            1886
#define IDC_CHB_B_RDO                   1886
#define IDC_LBL_PROPS_BREAKS            1887
#define IDC_LBL_AUTOLOAD_SEPARATE       1888
#define IDC_LBL_CONVOLVER_MIXINGSTRENGTH 1889
#define IDC_TBR_CONVOLVER_MIXINGSTRENGTH 1890
#define IDC_CHB_CONVOLVER_LEVELADJUST_AUTO 1891
#define IDC_CHB_RESIZE_METHOD_LOCK      1892
#define IDC_LBL_CONVOLVER_LEVELADJUSTDB 1893
#define IDC_TBR_CONVOLVER_LEVELADJUSTDB 1894
#define IDC_LBL_CONVOLVER_WAV_FORMAT2   1897
#define IDC_CBX_POSTPROC_H264           1898
#define IDC_LBL_POSTPROC_H264           1899
#define IDC_LV_CONVOLVER_FILES          1900
#define IDC_BT_CONVOLVER_FILES_SET      1902
#define IDC_BT_CONVOLVER_FILES_CLEAR    1903
#define IDC_CHB_CONVOLVER_MAPPING       1905
#define IDC_PLC_AUTOLOAD_ITEMS          1906
#define IDC_LV_INFO                     1907
#define IDC_CBX_QUANT_TABLE             1908
#define IDC_CHB_LEVELS_INPUT_AUTO       1909
#define IDC_LBL_OUT_DV_PROFILE          1910
#define IDC_CBX_OUT_DV_PROFILE          1911
#define IDC_LBL_OUT_PLANAR_YUV          1912
#define IDC_LBL_OUT_PACKED_YUV          1913
#define IDC_LBL_OUT_RGB                 1914
#define IDC_BT_PRESETAUTOLOAD_SIZE_COMP 1915
#define IDC_BT_QUANTMATRIX_EXPORT       1916
#define IDC_BT_DCT_MPEG                 1917
#define IDC_RBT_DCT_H263                1919
#define IDC_LBL_DCT_QUANT               1920
#define IDC_TBR_DCT_QUANT               1921
#define IDC_RBT_DCT_MPEG                1922
#define IDC_CHB_VOLUME_L_MUTE           1922
#define IDC_CHB_VOLUME_L_SOLO           1923
#define IDC_CHB_VOLUME_C_MUTE           1924
#define IDC_LBX_LEVELS_CURVES           1924
#define IDC_CHB_VOLUME_C_SOLO           1925
#define IDC_CHB_VOLUME_R_MUTE           1926
#define IDC_CHB_VOLUME_R_SOLO           1927
#define IDC_CHB_VOLUME_SL_MUTE          1928
#define IDC_CHB_VOLUME_SL_SOLO          1929
#define IDC_CHB_VOLUME_SR_MUTE          1930
#define IDC_CHB_VOLUME_SR_SOLO          1931
#define IDC_CBX_SCANLINE                1931
#define IDC_CHB_VOLUME_LFE_MUTE         1932
#define IDC_LBL_SCANLINE                1932
#define IDC_CHB_VOLUME_LFE_SOLO         1933
#define IDC_BT_LEVELS_CURVES_LOAD       1933
#define IDC_CHB_MIXER_LFE               1934
#define IDC_CHB_BLACKLIST               1935
#define IDC_ED_BLACKLIST                1936
#define IDC_CHB_VOL_DB                  1937
#define IDC_CBX_DV_PROFILE              1938
#define IDC_CHB_TRANSFORM_FLIP          1939
#define IDC_CHB_TRANSFORM_FLIP2         1940
#define IDC_CHB_TRANSFORM_MIRROR        1940
#define IDC_CHB_GRADFUN                 1940
#define IDC_LBL_GRADFUN_THRESHOLD       1941
#define IDC_TBR_GRADFUN_THRESHOLD       1942
#define IDC_CHB_DROP_ON_DELAY           1943
#define IDC_CHB_MULTITHREAD             1944
#define IDC_CHB_DONT_QUEUE_IN_WMP       1945
#define IDC_GRP_H264OUALITYCONTROL      1946
#define IDC_CHB_H264_SKIP_ON_DELAY      1947
#define IDC_ED_DROP_ON_DELAY_TIME       1948
#define IDC_TXT_MS                      1950
#define IDC_ED_H264SKIP_ON_DELAY_TIME   1951
#define IDC_TXT_MS2                     1952
#define IDC_CHB_RESIZE_ACCURATE_ROUNDING 1953
#define IDC_GRP_QUEUE                   1954
#define IDC_CHB_NORMALIZE_RESETONSEEK   1957
#define IDC_CHB_USE_QUEUE_ONLY_IN       1958
#define IDC_ED_USE_QUEUE_ONLY_IN_LIST   1959
#define IDC_CMB_H264_SKIP_METHOD        1960
#define IDC_CHB_FILTER_SKIP             1961
#define IDC_LBL_METHOD                  1962
#define IDC_LBL_DELAY_DROP              1963
#define IDC_LBL_DELAY_H264              1964
#define IDC_CBX_OUT_HWDEINT_METHOD      1965
#define IDC_TXT_OUT_DEINT_METHOD        1966
#define IDC_ED_SUB_SEARCH_EXT           1967
#define IDC_TXT_SERCH_ORDER             1968
#define IDC_CHB_COMPATIBILITYLIST       1970
#define IDC_ED_COMPATIBILITYLIST        1971
#define IDC_TXT_COMPATIBILITYLIST       1972
#define IDC_BT_BLACKLIST                1973
#define IDC_BT_COMPATIBILITYLIST        1974
#define IDC_BT_ADDCOMPATIBLEFILE        1975
#define IDC_BT_COMP_RESET               1976
#define IDC_CBX_FONT_SUBSHADOW_MODE     1977
#define IDC_LBL_FONT_SUBSHADOW_MODE     1978
#define IDC_TBR_FONT_SUBSHADOW_SIZE     1979
#define IDC_LBL_FONT_SUBSHADOW_ALPHA    1981
#define IDC_TBR_FONT_SUBSHADOW_ALPHA    1982
#define IDC_CBX_AOUT_MULTICHANNEL_DEVICE 1983
#define IDC_LBL_AOUT_MULTICHANNEL_DEVICE 1984
#define IDC_CHB_AOUT_AC3ENCODE_MODE     1985
#define IDC_RBT_RESIZE_MODE_SIZE        1986
#define IDC_RBT_RESIZE_MODE_SIZE_H      1987
#define IDC_CHB_SAR_INTERNALLY          1988
#define IDC_CHB_WINAMP_MULTICHANNEL     1989
#define IDC_CHB_MMX                     2000
#define IDC_CHB_MMXEXT                  2001
#define IDC_CHB_SSE                     2002
#define IDC_CHB_SSE2                    2003
#define IDC_CHB_SSE3                    2004
#define IDC_CHB_SSSE3                   2005
#define IDC_CHB_3DNOW                   2006
#define IDC_CHB_3DNOWEXT                2007
#define IDC_CHB_ALLOW_MMX               2008
#define IDC_CHB_ALLOW_MMXEXT            2009
#define IDC_CHB_ALLOW_SSE               2010
#define IDC_CHB_ALLOW_SSE2              2011
#define IDC_CHB_ALLOW_SSE3              2012
#define IDC_CHB_ALLOW_SSSE3             2013
#define IDC_CHB_ALLOW_3DNOW             2014
#define IDC_CHB_ALLOW_3DNOWEXT          2015
#define IDC_RBT_ICON_NONE               2016
#define IDC_RBT_ICON_MODERN             2017
#define IDC_RBT_ICON_CLASSIC            2018
#define IDC_TXT_TRAYICON                2019
#define IDD_INFOSIMD                    2020
#define IDC_CHB_AVISYNTH_FFDSHOW        2021
#define IDC_CBX_AVISYNTH_PULLDOWN       2022
#define IDC_LBL_AVISYNTH_PULLDOWN       2023
#define IDC_LBL_AVISYNTH_CSPIN          2024
#define IDC_CHB_AVISYNTH_YV12           2025
#define IDC_CHB_AVISYNTH_YUY2           2026
#define IDC_CHB_AVISYNTH_RGB24          2027
#define IDC_CHB_AVISYNTH_RGB32          2028
#define IDC_CHB_AVISYNTH_BUFFER         2029
#define IDC_ED_AVISYNTH_BUF_BACK        2030
#define IDC_ED_AVISYNTH_BUF_AHEAD       2031
#define IDC_BT_AVISYNTH_USECURRENT      2032
#define IDC_BT_AVISYNTH_LOAD            2033
#define IDC_BT_AVISYNTH_SAVE            2034
#define IDC_TXT_COMP_1                  2041
#define IDC_TXT_COMP_2                  2042
#define IDC_CHB_COMP_DONTASK            2043
#define IDC_CHB_COMP_SEND               2044
#define IDC_RBT_COMP_1                  2045
#define IDC_RBT_COMP_2                  2046
#define IDC_RBT_COMP_3                  2047
#define IDC_RBT_COMP_4                  2048
#define IDC_GRP_COMP_1                  2049
#define IDC_EDT_COMP_1                  2050
#define IDC_CHB_IS_COMPMGR              2051
#define IDC_TXT_FONT_BODY               2052
#define IDC_TXT_FONT_OUTLINE            2053
#define IDC_TXT_SHADOW                  2054
#define IDC_TXT_FONT_SHADOW             2054
#define IDC_TBR_FONT_BODY_ALPHA         2056
#define IDC_TBR_FONT_OUTLINE_ALPHA      2059
#define IDC_FONT_OPAQUE_BOX             2060
#define IDC_IMG_FONT_COLOR_OUTLINE      2061
#define IDC_IMG_FONT_COLOR_SHADOW       2062
#define IDC_LBL_FONT_OUTLINE_WIDTH      2063
#define IDC_TBR_FONT_OUTLINE_WIDTH      2064
#define IDC_GRP_FONT_COLOR              2065
#define IDC_CBX_SUB_WORDWRAP            2066
#define IDC_GRP_RESIZE_BORDERS_DIV      2067
#define IDC_LBL_BORDER_LEFT             2068
#define IDC_LBL_BORDER_RIGHT            2069
#define IDC_LBL_BORDER_TOP              2070
#define IDC_LBL_BORDER_BOTTOM           2071
#define IDC_LBL_BORDER_LEFT_NUM         2073
#define IDC_LBL_BORDER_TOP_NUM          2074
#define IDC_LBL_BORDER_RIGHT_NUM        2075
#define IDC_LBL_BORDER_BOTTOM_NUM       2076
#define IDC_TBR_BORDER_HORIZ_DIV        2077
#define IDC_TBR_BORDER_VERT_DIV         2078
#define IDC_LBL_BORDER_HORIZ_DIV        2079
#define IDC_LBL_BORDER_VERT_DIV         2080
#define IDC_CHB_FONT_BLUR               2081
#define IDC_ED_RESIZE_OUT_DEVICE_A1     2082
#define IDC_ED_RESIZE_OUT_DEVICE_A2     2083
#define IDC_LBL_PAR_OUTDEV              2084
#define IDC_LBL_NEW_ASPECT_SEP2         2085
#define IDC_RBT_RESIZE_MODE_SCREEN_RES  2086
#define IDC_CHB_FONT_OVERRIDE_SCALING   2087
#define IDC_CHB_FONT_ASPECT_AUTO        2088
#define IDC_TBR_FONT_YSCALE             2089
#define IDC_LBL_FONT_YSCALE             2090
#define IDC_GRP_AUTOCROP                2091
#define IDC_CHB_CODEC_OPT3              2092
#define IDC_CHB_CODEC_OPT4              2093
#define IDC_LBL_CROP_TOLERANCE          2094
#define IDC_ED_CROP_TOLERANCE           2095
#define IDC_LBL_CROP_REFRESH            2096
#define IDC_ED_CROP_REFRESH             2097
#define IDC_RBT_AUTOCROPV               2098
#define IDC_RBT_AUTOCROPH               2099
#define IDC_RBT_AUTOCROPVH              2100
#define IDC_LBL_CROP_STOPSCAN           2101
#define IDC_ED_CROP_STOPSCAN            2102
#define IDC_LBL_Y_MAX_DELTA             2103
#define IDC_UD_Y_MAX_DELTA              2104
#define IDC_ED_Y_MAX_DELTA              2105
#define IDC_LBL_Y_THRESHOLD             2106
#define IDC_UD_Y_THRESHOLD              2107
#define IDC_ED_Y_THRESHOLD              2108
#define IDC_LBL_Y_TEMPORAL              2109
#define IDC_UD_Y_TEMPORAL               2110
#define IDC_ED_Y_TEMPORAL               2111
#define IDD_CSP_OPTIONS                 2112
#define IDC_RBT_BT601                   2113
#define IDC_RBT_BT709                   2114
#define IDC_TBR_RGBCONV_WHITE           2115
#define IDC_TBR_RGBCONV_BLACK           2116
#define IDC_TBR_RGBCONV_CHROMA          2117
#define IDC_TXT_RGBCONV_BLACK           2118
#define IDC_TXT_RGBCONV_WHITE           2119
#define IDC_TXT_RGBCONV_CHROMA          2120
#define IDC_CHB_RGBCONV_CHROMA_LOCK     2121
#define IDC_GRP_CSP_OPT2                2122
#define IDC_GRP_CSP_OPT1                2123
#define IDC_RBT_REC_YUV                 2124
#define IDC_RBT_PC_YUV                  2125
#define IDC_RBT_CUSTOM_YUV              2126
#define IDC_ED_MIXERMATRIX06            2127
#define IDC_ED_MIXERMATRIX07            2128
#define IDC_ED_MIXERMATRIX08            2129
#define IDC_ED_MIXERMATRIX16            2130
#define IDC_ED_MIXERMATRIX17            2131
#define IDC_ED_MIXERMATRIX18            2132
#define IDC_ED_MIXERMATRIX26            2133
#define IDC_ED_MIXERMATRIX27            2134
#define IDC_ED_MIXERMATRIX28            2135
#define IDC_ED_MIXERMATRIX36            2136
#define IDC_ED_MIXERMATRIX37            2137
#define IDC_ED_MIXERMATRIX38            2138
#define IDC_ED_MIXERMATRIX46            2139
#define IDC_ED_MIXERMATRIX47            2140
#define IDC_ED_MIXERMATRIX48            2141
#define IDC_ED_MIXERMATRIX56            2142
#define IDC_ED_MIXERMATRIX57            2143
#define IDC_ED_MIXERMATRIX58            2144
#define IDC_ED_MIXERMATRIX60            2145
#define IDC_ED_MIXERMATRIX61            2146
#define IDC_ED_MIXERMATRIX62            2147
#define IDC_ED_MIXERMATRIX63            2148
#define IDC_ED_MIXERMATRIX64            2149
#define IDC_ED_MIXERMATRIX65            2150
#define IDC_ED_MIXERMATRIX66            2151
#define IDC_ED_MIXERMATRIX67            2152
#define IDC_ED_MIXERMATRIX68            2153
#define IDC_ED_MIXERMATRIX70            2154
#define IDC_ED_MIXERMATRIX71            2155
#define IDC_ED_MIXERMATRIX72            2156
#define IDC_ED_MIXERMATRIX73            2157
#define IDC_ED_MIXERMATRIX74            2158
#define IDC_ED_MIXERMATRIX75            2159
#define IDC_ED_MIXERMATRIX76            2160
#define IDC_ED_MIXERMATRIX77            2161
#define IDC_ED_MIXERMATRIX78            2162
#define IDC_ED_MIXERMATRIX80            2163
#define IDC_ED_MIXERMATRIX81            2164
#define IDC_ED_MIXERMATRIX82            2165
#define IDC_ED_MIXERMATRIX83            2166
#define IDC_ED_MIXERMATRIX84            2167
#define IDC_ED_MIXERMATRIX85            2168
#define IDC_ED_MIXERMATRIX86            2169
#define IDC_ED_MIXERMATRIX87            2170
#define IDC_ED_MIXERMATRIX88            2171
#define IDC_LBL_MIXERMATRIX_AL          2172
#define IDC_LBL_MIXERMATRIX_AR          2173
#define IDC_LBL_MIXERMATRIX_AL1         2174
#define IDC_LBL_MIXERMATRIX_AR1         2175
#define IDC_LBL_MIXERMATRIX_BC          2176
#define IDC_LBL_MIXERMATRIX_BC1         2177
#define IDC_LBL_DELAY_AL                2178
#define IDC_ED_DELAY_AL                 2179
#define IDC_LBL_DELAY_AL2               2180
#define IDC_LBL_DELAY_AR                2181
#define IDC_ED_DELAY_AR                 2182
#define IDC_LBL_DELAY_AR2               2183
#define IDC_LBL_DELAY_BC                2184
#define IDC_LBL_DELAY_SL4               2185
#define IDC_LBL_DELAY_BC2               2186
#define IDC_ED_DELAY_BC                 2187
#define IDC_LBL_CHANNELSWAP_AL          2188
#define IDC_LBL_CHANNELSWAP_AL2         2189
#define IDC_CBX_CHANNELSWAP_AL          2190
#define IDC_LBL_CHANNELSWAP_AR          2191
#define IDC_LBL_CHANNELSWAP_AR2         2192
#define IDC_CBX_CHANNELSWAP_AR          2193
#define IDC_LBL_VOLUME_AL               2194
#define IDC_LBL_VOLUME_AR               2195
#define IDC_LBL_VOLUME_AL2              2196
#define IDC_LBL_VOLUME_AR2              2197
#define IDC_TBR_VOLUME_AL               2198
#define IDC_TBR_VOLUME_AR               2199
#define IDC_CHB_VOLUME_AR_SOLO          2200
#define IDC_CHB_VOLUME_AR_MUTE          2201
#define IDC_CHB_VOLUME_AL_MUTE          2202
#define IDC_CHB_VOLUME_AL_SOLO          2203
#define IDC_PBR_VOLUME_AR               2204
#define IDC_PBR_VOLUME_AL               2205
#define IDC_CHB_QUEUE_VMR9YV12          2206
#define IDC_RBT_PRESETAUTOLOAD_OR       2207
#define IDC_RBT_PRESETAUTOLOAD_AND      2208
#define IDC_LBL_BORDER_BRIGHTNESS       2209
#define IDC_TBR_BORDER_BRIGHTNESS       2210
#define IDC_LBL_BORDER_BRIGHTNESS_NUM   2211
#define IDC_CHB_WRITEINFO2DBG           2212
#define IDC_ED_RESIZE_USER_ASPECT       2213
#define IDC_BT_RESIZE_USER_ASPECT       2214
#define IDC_LBL_USER_ASPECT_1           2215
#define IDC_CBX_OSD_USERFORMAT          2217
#define IDC_LBL_OSD_USERFORMAT          2218
#define IDC_CHB_NORMALIZE_REGAINVOLUME  2219
#define IDC_CHB_DEINTERLACEALWAYS       2220
#define IDC_CBX_YADIF_PARITY            2221
#define IDC_LBL_YADIF_PARITY            2222
#define IDC_CHB_YADIF_SKIP_CHECK        2223
#define IDC_CHB_YADIF_DOUBLE_FRAMERATE  2224
#define IDC_BT_SUB_SSA_CONFIG           2226
#define IDC_CHB_SUB_SSA_OVERRIDE_POSITION 2227
#define IDC_CHB_SUB_SSA_OVERRIDE_SCALING 2228
#define IDC_CHB_SUB_SSA_USE_INPUT_DIMENSIONS 2229
#define IDD_SUBTITLES_SSA               2230
#define IDC_CHB_SUB_SSA_KEEP_TEXT_INSIDE 2231
#define IDC_CBX_OUT_HWDEINT_FIELDORDER  2232
#define IDC_TXT_OUT_DEINT_FIELDORDER    2233
#define IDC_GRP_SF_PASSTHROUGH          2234
#define IDC_CHB_PASSTHROUGH_AC3         2235
#define IDC_CHB_PASSTHROUGH_DTS         2236
#define IDC_LBL_BICUBIC_PARAM_TYPE      2237
#define IDC_CBX_BICUBIC_PARAM_TYPE      2238
#define IDC_LBL_BICUBIC_RINGING         2239
#define IDC_TBR_BICUBIC_RINGING         2240
#define IDC_GRP_CSP_OPT3                2241
#define IDC_CBX_RGB_INTERLACE_METHOD    2242
#define IDC_TXT_CSP_OPTIONS_INTERLACE_OR_PROGRESSIVE 2243
#define IDD_AUDIODECODEROPTIONS         2244
#define IDC_CHB_AUDIO_DECODER_DRC       2245
#define IDC_TBR_DECODER_DRC_LEVEL       2246
#define IDC_LBL_DECODER_DRC_LEVEL       2247
#define ID_MNI_PRESET_NEWFROMDEFAULT    40004
#define ID_MNI_PRESET_NEWFROMSELECTED   40005
#define ID_MNI_PRESET_NEW_FROMFILE      40006
#define ID_MNI_PRESET_RENAMETOEXE       40010
#define ID_TRANSLATE_CONTROLCAPTION     40011
#define ID_TRANSLATE_ASSOCIATEDSTRINGS  40012
#define IDC_STATIC                      -1
#define IDC_GRP_WINAMP2                 65535

//OpenSVCDecoder stuffs
#define IDD_OPENSVCDECODER				2250
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         2244
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
